/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.3
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.revolsys.gis.esri.gdb.file.capi.swig;

public class ByteArray {
  public static long getCPtr(final ByteArray obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  private long swigCPtr;

  protected boolean swigCMemOwn;

  public ByteArray() {
    this(EsriFileGdbJNI.new_ByteArray__SWIG_1(), true);
  }

  public ByteArray(final long length) {
    this(EsriFileGdbJNI.new_ByteArray__SWIG_0(length), true);
  }

  public ByteArray(final long cPtr, final boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public boolean Allocate(final long length) {
    return EsriFileGdbJNI.ByteArray_Allocate(swigCPtr, this, length);
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        EsriFileGdbJNI.delete_ByteArray(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  @Override
  protected void finalize() {
    delete();
  }

  public short get(final int i) {
    return EsriFileGdbJNI.ByteArray_get(swigCPtr, this, i);
  }

  public long getAllocatedLength() {
    return EsriFileGdbJNI.ByteArray_allocatedLength_get(swigCPtr, this);
  }

  public long getInUseLength() {
    return EsriFileGdbJNI.ByteArray_inUseLength_get(swigCPtr, this);
  }

  public void set(final int i, final short c) {
    EsriFileGdbJNI.ByteArray_set(swigCPtr, this, i, c);
  }

  public void setAllocatedLength(final long value) {
    EsriFileGdbJNI.ByteArray_allocatedLength_set(swigCPtr, this, value);
  }

  public void setInUseLength(final long value) {
    EsriFileGdbJNI.ByteArray_inUseLength_set(swigCPtr, this, value);
  }

}
