/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.3
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.revolsys.gis.esri.gdb.file.capi.swig;

public class DoubleArray {
  public static long getCPtr(final DoubleArray obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  private long swigCPtr;

  protected boolean swigCMemOwn;

  public DoubleArray() {
    this(EsriFileGdbJNI.new_DoubleArray(), true);
  }

  public DoubleArray(final long cPtr, final boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        EsriFileGdbJNI.delete_DoubleArray(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  @Override
  protected void finalize() {
    delete();
  }

  public double get(final int i) {
    return EsriFileGdbJNI.DoubleArray_get(swigCPtr, this, i);
  }

  public void set(final int i, final double value) {
    EsriFileGdbJNI.DoubleArray_set(swigCPtr, this, i, value);
  }

}
