/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.3
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.revolsys.gis.esri.gdb.file.capi.swig;

public class EnumRows {
  public static long getCPtr(final EnumRows obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  private long swigCPtr;

  protected boolean swigCMemOwn;

  public EnumRows() {
    this(EsriFileGdbJNI.new_EnumRows(), true);
  }

  public EnumRows(final long cPtr, final boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public void Close() {
    EsriFileGdbJNI.EnumRows_Close(swigCPtr, this);
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        EsriFileGdbJNI.delete_EnumRows(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  @Override
  protected void finalize() {
    delete();
  }

  public int GetFieldInformation(final FieldInfo fieldInfo) {
    return EsriFileGdbJNI.EnumRows_GetFieldInformation(swigCPtr, this,
      FieldInfo.getCPtr(fieldInfo), fieldInfo);
  }

  public VectorOfFieldDef getFields() {
    return new VectorOfFieldDef(EsriFileGdbJNI.EnumRows_getFields(swigCPtr,
      this), true);
  }

  public Row next() {
    final long cPtr = EsriFileGdbJNI.EnumRows_next(swigCPtr, this);
    return (cPtr == 0) ? null : new Row(cPtr, true);
  }

}
