/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.revolsys.gis.esri.gdb.file.capi.swig;

public class FieldInfo {
  protected static long getCPtr(final FieldInfo obj) {
    return obj == null ? 0 : obj.swigCPtr;
  }

  private long swigCPtr;

  protected boolean swigCMemOwn;

  public FieldInfo() {
    this(EsriFileGdbJNI.new_FieldInfo(), true);
  }

  protected FieldInfo(final long cPtr, final boolean cMemoryOwn) {
    this.swigCMemOwn = cMemoryOwn;
    this.swigCPtr = cPtr;
  }

  public synchronized void delete() {
    if (this.swigCPtr != 0) {
      if (this.swigCMemOwn) {
        this.swigCMemOwn = false;
        EsriFileGdbJNI.delete_FieldInfo(this.swigCPtr);
      }
      this.swigCPtr = 0;
    }
  }

  @Override
  protected void finalize() {
    delete();
  }

  public int getFieldCount() {
    return EsriFileGdbJNI.FieldInfo_getFieldCount(this.swigCPtr, this);
  }

  public int getFieldLength(final int i) {
    return EsriFileGdbJNI.FieldInfo_getFieldLength(this.swigCPtr, this, i);
  }

  public String getFieldName(final int i) {
    return EsriFileGdbJNI.FieldInfo_getFieldName(this.swigCPtr, this, i);
  }

  public FieldType getFieldType(final int i) {
    return FieldType.swigToEnum(EsriFileGdbJNI.FieldInfo_getFieldType(this.swigCPtr, this, i));
  }

  public boolean isNullable(final int i) {
    return EsriFileGdbJNI.FieldInfo_isNullable(this.swigCPtr, this, i);
  }

}
