/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.3
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.revolsys.gis.esri.gdb.file.capi.swig;

public class FieldInfo {
  public static long getCPtr(final FieldInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  private long swigCPtr;

  protected boolean swigCMemOwn;

  public FieldInfo() {
    this(EsriFileGdbJNI.new_FieldInfo(), true);
  }

  public FieldInfo(final long cPtr, final boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        EsriFileGdbJNI.delete_FieldInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  @Override
  protected void finalize() {
    delete();
  }

  public int getFieldCount() {
    return EsriFileGdbJNI.FieldInfo_getFieldCount(swigCPtr, this);
  }

  public int getFieldLength(final int i) {
    return EsriFileGdbJNI.FieldInfo_getFieldLength(swigCPtr, this, i);
  }

  public String getFieldName(final int i) {
    return EsriFileGdbJNI.FieldInfo_getFieldName(swigCPtr, this, i);
  }

  public FieldType getFieldType(final int i) {
    return FieldType.swigToEnum(EsriFileGdbJNI.FieldInfo_getFieldType(swigCPtr,
      this, i));
  }

  public boolean isNullable(final int i) {
    return EsriFileGdbJNI.FieldInfo_isNullable(swigCPtr, this, i);
  }

}
