/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.3
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.revolsys.gis.esri.gdb.file.capi.swig;

public class FloatArray {
  public static long getCPtr(final FloatArray obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  private long swigCPtr;

  protected boolean swigCMemOwn;

  public FloatArray() {
    this(EsriFileGdbJNI.new_FloatArray(), true);
  }

  public FloatArray(final long cPtr, final boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        EsriFileGdbJNI.delete_FloatArray(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  @Override
  protected void finalize() {
    delete();
  }

  public float get(final int i) {
    return EsriFileGdbJNI.FloatArray_get(swigCPtr, this, i);
  }

  public void set(final int i, final float value) {
    EsriFileGdbJNI.FloatArray_set(swigCPtr, this, i, value);
  }

}
