/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.3
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.revolsys.gis.esri.gdb.file.capi.swig;

public class GeometryDef {
  public static long getCPtr(final GeometryDef obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  private long swigCPtr;

  protected boolean swigCMemOwn;

  public GeometryDef() {
    this(EsriFileGdbJNI.new_GeometryDef(), true);
  }

  public GeometryDef(final long cPtr, final boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        EsriFileGdbJNI.delete_GeometryDef(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  @Override
  protected void finalize() {
    delete();
  }

  public GeometryType getGeometryType() {
    return GeometryType.swigToEnum(EsriFileGdbJNI.GeometryDef_getGeometryType(
      swigCPtr, this));
  }

  public int GetSpatialReference(final SpatialReference spatialReference) {
    return EsriFileGdbJNI.GeometryDef_GetSpatialReference(swigCPtr, this,
      SpatialReference.getCPtr(spatialReference), spatialReference);
  }

  public boolean hasM() {
    return EsriFileGdbJNI.GeometryDef_hasM(swigCPtr, this);
  }

  public boolean hasZ() {
    return EsriFileGdbJNI.GeometryDef_hasZ(swigCPtr, this);
  }

  public int SetGeometryType(final GeometryType geometryType) {
    return EsriFileGdbJNI.GeometryDef_SetGeometryType(swigCPtr, this,
      geometryType.swigValue());
  }

  public int SetHasM(final boolean hasM) {
    return EsriFileGdbJNI.GeometryDef_SetHasM(swigCPtr, this, hasM);
  }

  public int SetHasZ(final boolean hasZ) {
    return EsriFileGdbJNI.GeometryDef_SetHasZ(swigCPtr, this, hasZ);
  }

  public int SetSpatialReference(final SpatialReference spatialReference) {
    return EsriFileGdbJNI.GeometryDef_SetSpatialReference(swigCPtr, this,
      SpatialReference.getCPtr(spatialReference), spatialReference);
  }

}
