/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.revolsys.gis.esri.gdb.file.capi.swig;

public class GeometryDef {
  protected static long getCPtr(final GeometryDef obj) {
    return obj == null ? 0 : obj.swigCPtr;
  }

  private long swigCPtr;

  protected boolean swigCMemOwn;

  public GeometryDef() {
    this(EsriFileGdbJNI.new_GeometryDef(), true);
  }

  protected GeometryDef(final long cPtr, final boolean cMemoryOwn) {
    this.swigCMemOwn = cMemoryOwn;
    this.swigCPtr = cPtr;
  }

  public synchronized void delete() {
    if (this.swigCPtr != 0) {
      if (this.swigCMemOwn) {
        this.swigCMemOwn = false;
        EsriFileGdbJNI.delete_GeometryDef(this.swigCPtr);
      }
      this.swigCPtr = 0;
    }
  }

  @Override
  protected void finalize() {
    delete();
  }

  public GeometryType getGeometryType() {
    return GeometryType.swigToEnum(EsriFileGdbJNI.GeometryDef_getGeometryType(
      this.swigCPtr, this));
  }

  public int GetSpatialReference(final SpatialReference spatialReference) {
    return EsriFileGdbJNI.GeometryDef_GetSpatialReference(this.swigCPtr, this,
      SpatialReference.getCPtr(spatialReference), spatialReference);
  }

  public boolean hasM() {
    return EsriFileGdbJNI.GeometryDef_hasM(this.swigCPtr, this);
  }

  public boolean hasZ() {
    return EsriFileGdbJNI.GeometryDef_hasZ(this.swigCPtr, this);
  }

  public int SetGeometryType(final GeometryType geometryType) {
    return EsriFileGdbJNI.GeometryDef_SetGeometryType(this.swigCPtr, this,
      geometryType.swigValue());
  }

  public int SetHasM(final boolean hasM) {
    return EsriFileGdbJNI.GeometryDef_SetHasM(this.swigCPtr, this, hasM);
  }

  public int SetHasZ(final boolean hasZ) {
    return EsriFileGdbJNI.GeometryDef_SetHasZ(this.swigCPtr, this, hasZ);
  }

  public int SetSpatialReference(final SpatialReference spatialReference) {
    return EsriFileGdbJNI.GeometryDef_SetSpatialReference(this.swigCPtr, this,
      SpatialReference.getCPtr(spatialReference), spatialReference);
  }

}
