/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.3
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.revolsys.gis.esri.gdb.file.capi.swig;

public class Guid {
  public static long getCPtr(final Guid obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  private long swigCPtr;

  protected boolean swigCMemOwn;

  public Guid() {
    this(EsriFileGdbJNI.new_Guid(), true);
  }

  public Guid(final long cPtr, final boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public void Create() {
    EsriFileGdbJNI.Guid_Create(swigCPtr, this);
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        EsriFileGdbJNI.delete_Guid(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public boolean equal(final Guid other) {
    return EsriFileGdbJNI.Guid_equal(swigCPtr, this, Guid.getCPtr(other), other);
  }

  @Override
  protected void finalize() {
    delete();
  }

  public int FromString(final String guidString) {
    return EsriFileGdbJNI.Guid_FromString(swigCPtr, this, guidString);
  }

  public boolean notEqual(final Guid other) {
    return EsriFileGdbJNI.Guid_notEqual(swigCPtr, this, Guid.getCPtr(other),
      other);
  }

  public void SetNull() {
    EsriFileGdbJNI.Guid_SetNull(swigCPtr, this);
  }

  @Override
  public String toString() {
    return EsriFileGdbJNI.Guid_toString(swigCPtr, this);
  }

}
