/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.revolsys.gis.esri.gdb.file.capi.swig;

public class IndexDef {
  protected static long getCPtr(final IndexDef obj) {
    return obj == null ? 0 : obj.swigCPtr;
  }

  private long swigCPtr;

  protected boolean swigCMemOwn;

  public IndexDef() {
    this(EsriFileGdbJNI.new_IndexDef__SWIG_0(), true);
  }

  protected IndexDef(final long cPtr, final boolean cMemoryOwn) {
    this.swigCMemOwn = cMemoryOwn;
    this.swigCPtr = cPtr;
  }

  public IndexDef(final String name, final String fields) {
    this(EsriFileGdbJNI.new_IndexDef__SWIG_2(name, fields), true);
  }

  public IndexDef(final String name, final String fields, final boolean isUnique) {
    this(EsriFileGdbJNI.new_IndexDef__SWIG_1(name, fields, isUnique), true);
  }

  public synchronized void delete() {
    if (this.swigCPtr != 0) {
      if (this.swigCMemOwn) {
        this.swigCMemOwn = false;
        EsriFileGdbJNI.delete_IndexDef(this.swigCPtr);
      }
      this.swigCPtr = 0;
    }
  }

  @Override
  protected void finalize() {
    delete();
  }

  public String getFields() {
    return EsriFileGdbJNI.IndexDef_getFields(this.swigCPtr, this);
  }

  public String getName() {
    return EsriFileGdbJNI.IndexDef_getName(this.swigCPtr, this);
  }

  public boolean isUnique() {
    return EsriFileGdbJNI.IndexDef_isUnique(this.swigCPtr, this);
  }

  public int SetFields(final String fields) {
    return EsriFileGdbJNI.IndexDef_SetFields(this.swigCPtr, this, fields);
  }

  public int SetIsUnique(final boolean isUnique) {
    return EsriFileGdbJNI.IndexDef_SetIsUnique(this.swigCPtr, this, isUnique);
  }

  public int SetName(final String name) {
    return EsriFileGdbJNI.IndexDef_SetName(this.swigCPtr, this, name);
  }

}
