/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.3
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.revolsys.gis.esri.gdb.file.capi.swig;

public class IndexDef {
  public static long getCPtr(final IndexDef obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  private long swigCPtr;

  protected boolean swigCMemOwn;

  public IndexDef() {
    this(EsriFileGdbJNI.new_IndexDef__SWIG_0(), true);
  }

  public IndexDef(final long cPtr, final boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public IndexDef(final String name, final String fields) {
    this(EsriFileGdbJNI.new_IndexDef__SWIG_2(name, fields), true);
  }

  public IndexDef(final String name, final String fields, final boolean isUnique) {
    this(EsriFileGdbJNI.new_IndexDef__SWIG_1(name, fields, isUnique), true);
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        EsriFileGdbJNI.delete_IndexDef(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  @Override
  protected void finalize() {
    delete();
  }

  public String getFields() {
    return EsriFileGdbJNI.IndexDef_getFields(swigCPtr, this);
  }

  public String getName() {
    return EsriFileGdbJNI.IndexDef_getName(swigCPtr, this);
  }

  public boolean isUnique() {
    return EsriFileGdbJNI.IndexDef_isUnique(swigCPtr, this);
  }

  public int SetFields(final String fields) {
    return EsriFileGdbJNI.IndexDef_SetFields(swigCPtr, this, fields);
  }

  public int SetIsUnique(final boolean isUnique) {
    return EsriFileGdbJNI.IndexDef_SetIsUnique(swigCPtr, this, isUnique);
  }

  public int SetName(final String name) {
    return EsriFileGdbJNI.IndexDef_SetName(swigCPtr, this, name);
  }

}
