/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.3
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.revolsys.gis.esri.gdb.file.capi.swig;

public class Row {
  public static long getCPtr(final Row obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  private long swigCPtr;

  protected boolean swigCMemOwn;

  public Row() {
    this(EsriFileGdbJNI.new_Row(), true);
  }

  public Row(final long cPtr, final boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        EsriFileGdbJNI.delete_Row(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  @Override
  protected void finalize() {
    delete();
  }

  public int GetBinary(final String field, final ByteArray binaryBuf) {
    return EsriFileGdbJNI.Row_GetBinary(swigCPtr, this, field,
      ByteArray.getCPtr(binaryBuf), binaryBuf);
  }

  public long getDate(final String name) {
    return EsriFileGdbJNI.Row_getDate(swigCPtr, this, name);
  }

  public double getDouble(final String name) {
    return EsriFileGdbJNI.Row_getDouble(swigCPtr, this, name);
  }

  public int GetFieldInformation(final FieldInfo fieldInfo) {
    return EsriFileGdbJNI.Row_GetFieldInformation(swigCPtr, this,
      FieldInfo.getCPtr(fieldInfo), fieldInfo);
  }

  public VectorOfFieldDef getFields() {
    return new VectorOfFieldDef(EsriFileGdbJNI.Row_getFields(swigCPtr, this),
      true);
  }

  public float getFloat(final String name) {
    return EsriFileGdbJNI.Row_getFloat(swigCPtr, this, name);
  }

  public ShapeBuffer getGeometry() {
    final long cPtr = EsriFileGdbJNI.Row_getGeometry(swigCPtr, this);
    return (cPtr == 0) ? null : new ShapeBuffer(cPtr, true);
  }

  public Guid getGlobalId() {
    return new Guid(EsriFileGdbJNI.Row_getGlobalId(swigCPtr, this), true);
  }

  public Guid getGuid(final String name) {
    return new Guid(EsriFileGdbJNI.Row_getGuid(swigCPtr, this, name), true);
  }

  public int getInteger(final String name) {
    return EsriFileGdbJNI.Row_getInteger(swigCPtr, this, name);
  }

  public int getOid() {
    return EsriFileGdbJNI.Row_getOid(swigCPtr, this);
  }

  public short getShort(final String name) {
    return EsriFileGdbJNI.Row_getShort(swigCPtr, this, name);
  }

  public String getString(final String name) {
    return EsriFileGdbJNI.Row_getString(swigCPtr, this, name);
  }

  public String getXML(final String name) {
    return EsriFileGdbJNI.Row_getXML(swigCPtr, this, name);
  }

  public boolean isNull(final String name) {
    return EsriFileGdbJNI.Row_isNull(swigCPtr, this, name);
  }

  public int SetBinary(final String field, final ByteArray binaryBuf) {
    return EsriFileGdbJNI.Row_SetBinary(swigCPtr, this, field,
      ByteArray.getCPtr(binaryBuf), binaryBuf);
  }

  public void setDate(final String name, final long date) {
    EsriFileGdbJNI.Row_setDate(swigCPtr, this, name, date);
  }

  public void setDouble(final String name, final double value) {
    EsriFileGdbJNI.Row_setDouble(swigCPtr, this, name, value);
  }

  public void setFloat(final String name, final double value) {
    EsriFileGdbJNI.Row_setFloat(swigCPtr, this, name, value);
  }

  public void setGeometry(final ShapeBuffer value) {
    EsriFileGdbJNI.Row_setGeometry(swigCPtr, this, ShapeBuffer.getCPtr(value),
      value);
  }

  public void setGuid(final String name, final Guid value) {
    EsriFileGdbJNI.Row_setGuid(swigCPtr, this, name, Guid.getCPtr(value), value);
  }

  public void setInteger(final String name, final int value) {
    EsriFileGdbJNI.Row_setInteger(swigCPtr, this, name, value);
  }

  public void setNull(final String name) {
    EsriFileGdbJNI.Row_setNull(swigCPtr, this, name);
  }

  public void setShort(final String name, final short value) {
    EsriFileGdbJNI.Row_setShort(swigCPtr, this, name, value);
  }

  public void setString(final String name, final String value) {
    EsriFileGdbJNI.Row_setString(swigCPtr, this, name, value);
  }

  public void setXML(final String name, final String value) {
    EsriFileGdbJNI.Row_setXML(swigCPtr, this, name, value);
  }

}
