/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.3
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.revolsys.gis.esri.gdb.file.capi.swig;

public class ShapeBuffer {
  public static long getCPtr(final ShapeBuffer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static boolean HasCurves(final ShapeType shapeType) {
    return EsriFileGdbJNI.ShapeBuffer_HasCurves(shapeType.swigValue());
  }

  public static boolean HasIDs(final ShapeType shapeType) {
    return EsriFileGdbJNI.ShapeBuffer_HasIDs(shapeType.swigValue());
  }

  public static boolean HasMaterials(final ShapeType shapeType) {
    return EsriFileGdbJNI.ShapeBuffer_HasMaterials(shapeType.swigValue());
  }

  public static boolean HasMs(final ShapeType shapeType) {
    return EsriFileGdbJNI.ShapeBuffer_HasMs(shapeType.swigValue());
  }

  public static boolean HasNormals(final ShapeType shapeType) {
    return EsriFileGdbJNI.ShapeBuffer_HasNormals(shapeType.swigValue());
  }

  public static boolean HasTextures(final ShapeType shapeType) {
    return EsriFileGdbJNI.ShapeBuffer_HasTextures(shapeType.swigValue());
  }

  public static boolean HasZs(final ShapeType shapeType) {
    return EsriFileGdbJNI.ShapeBuffer_HasZs(shapeType.swigValue());
  }

  private long swigCPtr;

  protected boolean swigCMemOwn;

  public ShapeBuffer() {
    this(EsriFileGdbJNI.new_ShapeBuffer__SWIG_1(), true);
  }

  public ShapeBuffer(final long length) {
    this(EsriFileGdbJNI.new_ShapeBuffer__SWIG_0(length), true);
  }

  public ShapeBuffer(final long cPtr, final boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public boolean Allocate(final long length) {
    return EsriFileGdbJNI.ShapeBuffer_Allocate(swigCPtr, this, length);
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        EsriFileGdbJNI.delete_ShapeBuffer(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  @Override
  protected void finalize() {
    delete();
  }

  public short get(final int i) {
    return EsriFileGdbJNI.ShapeBuffer_get(swigCPtr, this, i);
  }

  public long getAllocatedLength() {
    return EsriFileGdbJNI.ShapeBuffer_allocatedLength_get(swigCPtr, this);
  }

  public GeometryType getGeometryType() {
    return GeometryType.swigToEnum(EsriFileGdbJNI.ShapeBuffer_getGeometryType(
      swigCPtr, this));
  }

  public long getInUseLength() {
    return EsriFileGdbJNI.ShapeBuffer_inUseLength_get(swigCPtr, this);
  }

  public UnsignedCharArray getShapeBuffer() {
    return new UnsignedCharArray(EsriFileGdbJNI.ShapeBuffer_getShapeBuffer(
      swigCPtr, this), false);
  }

  public ShapeType getShapeType() {
    return ShapeType.swigToEnum(EsriFileGdbJNI.ShapeBuffer_getShapeType(
      swigCPtr, this));
  }

  public boolean IsEmpty() {
    return EsriFileGdbJNI.ShapeBuffer_IsEmpty(swigCPtr, this);
  }

  public void set(final int i, final short c) {
    EsriFileGdbJNI.ShapeBuffer_set(swigCPtr, this, i, c);
  }

  public void setAllocatedLength(final long value) {
    EsriFileGdbJNI.ShapeBuffer_allocatedLength_set(swigCPtr, this, value);
  }

  public void SetEmpty() {
    EsriFileGdbJNI.ShapeBuffer_SetEmpty(swigCPtr, this);
  }

  public void setInUseLength(final long value) {
    EsriFileGdbJNI.ShapeBuffer_inUseLength_set(swigCPtr, this, value);
  }

}
