/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.3
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.revolsys.gis.esri.gdb.file.capi.swig;

public class VectorOfWString {
  public static long getCPtr(final VectorOfWString obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  private long swigCPtr;

  protected boolean swigCMemOwn;

  public VectorOfWString() {
    this(EsriFileGdbJNI.new_VectorOfWString__SWIG_0(), true);
  }

  public VectorOfWString(final long n) {
    this(EsriFileGdbJNI.new_VectorOfWString__SWIG_1(n), true);
  }

  public VectorOfWString(final long cPtr, final boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public void add(final String x) {
    EsriFileGdbJNI.VectorOfWString_add(swigCPtr, this, x);
  }

  public long capacity() {
    return EsriFileGdbJNI.VectorOfWString_capacity(swigCPtr, this);
  }

  public void clear() {
    EsriFileGdbJNI.VectorOfWString_clear(swigCPtr, this);
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        EsriFileGdbJNI.delete_VectorOfWString(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  @Override
  protected void finalize() {
    delete();
  }

  public String get(final int i) {
    return EsriFileGdbJNI.VectorOfWString_get(swigCPtr, this, i);
  }

  public boolean isEmpty() {
    return EsriFileGdbJNI.VectorOfWString_isEmpty(swigCPtr, this);
  }

  public void reserve(final long n) {
    EsriFileGdbJNI.VectorOfWString_reserve(swigCPtr, this, n);
  }

  public void set(final int i, final String val) {
    EsriFileGdbJNI.VectorOfWString_set(swigCPtr, this, i, val);
  }

  public long size() {
    return EsriFileGdbJNI.VectorOfWString_size(swigCPtr, this);
  }

}
