// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/protobuf/fileformat.proto

package com.revolsys.io.openstreetmap.pbf;

public final class Fileformat {
  public static final class Blob extends
    com.google.protobuf.GeneratedMessageLite implements BlobOrBuilder {
    public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<Blob, Builder> implements
      BlobOrBuilder {
      private static Builder create() {
        return new Builder();
      }

      private int bitField0_;

      // optional bytes raw = 1;
      private com.google.protobuf.ByteString raw_ = com.google.protobuf.ByteString.EMPTY;

      // optional int32 raw_size = 2;
      private int rawSize_;

      // optional bytes zlib_data = 3;
      private com.google.protobuf.ByteString zlibData_ = com.google.protobuf.ByteString.EMPTY;

      // optional bytes lzma_data = 4;
      private com.google.protobuf.ByteString lzmaData_ = com.google.protobuf.ByteString.EMPTY;

      // optional bytes OBSOLETE_bzip2_data = 5 [deprecated = true];
      private com.google.protobuf.ByteString oBSOLETEBzip2Data_ = com.google.protobuf.ByteString.EMPTY;

      // Construct using Blob.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      @Override
      public Blob build() {
        final Blob result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      private Blob buildParsed()
        throws com.google.protobuf.InvalidProtocolBufferException {
        final Blob result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result).asInvalidProtocolBufferException();
        }
        return result;
      }

      @Override
      public Blob buildPartial() {
        final Blob result = new Blob(this);
        final int from_bitField0_ = this.bitField0_;
        int to_bitField0_ = 0;
        if ((from_bitField0_ & 0x00000001) == 0x00000001) {
          to_bitField0_ |= 0x00000001;
        }
        result.raw_ = this.raw_;
        if ((from_bitField0_ & 0x00000002) == 0x00000002) {
          to_bitField0_ |= 0x00000002;
        }
        result.rawSize_ = this.rawSize_;
        if ((from_bitField0_ & 0x00000004) == 0x00000004) {
          to_bitField0_ |= 0x00000004;
        }
        result.zlibData_ = this.zlibData_;
        if ((from_bitField0_ & 0x00000008) == 0x00000008) {
          to_bitField0_ |= 0x00000008;
        }
        result.lzmaData_ = this.lzmaData_;
        if ((from_bitField0_ & 0x00000010) == 0x00000010) {
          to_bitField0_ |= 0x00000010;
        }
        result.oBSOLETEBzip2Data_ = this.oBSOLETEBzip2Data_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      @Override
      public Builder clear() {
        super.clear();
        this.raw_ = com.google.protobuf.ByteString.EMPTY;
        this.bitField0_ = this.bitField0_ & ~0x00000001;
        this.rawSize_ = 0;
        this.bitField0_ = this.bitField0_ & ~0x00000002;
        this.zlibData_ = com.google.protobuf.ByteString.EMPTY;
        this.bitField0_ = this.bitField0_ & ~0x00000004;
        this.lzmaData_ = com.google.protobuf.ByteString.EMPTY;
        this.bitField0_ = this.bitField0_ & ~0x00000008;
        this.oBSOLETEBzip2Data_ = com.google.protobuf.ByteString.EMPTY;
        this.bitField0_ = this.bitField0_ & ~0x00000010;
        return this;
      }

      public Builder clearLzmaData() {
        this.bitField0_ = this.bitField0_ & ~0x00000008;
        this.lzmaData_ = getDefaultInstance().getLzmaData();

        return this;
      }

      @java.lang.Deprecated
      public Builder clearOBSOLETEBzip2Data() {
        this.bitField0_ = this.bitField0_ & ~0x00000010;
        this.oBSOLETEBzip2Data_ = getDefaultInstance().getOBSOLETEBzip2Data();

        return this;
      }

      public Builder clearRaw() {
        this.bitField0_ = this.bitField0_ & ~0x00000001;
        this.raw_ = getDefaultInstance().getRaw();

        return this;
      }

      public Builder clearRawSize() {
        this.bitField0_ = this.bitField0_ & ~0x00000002;
        this.rawSize_ = 0;

        return this;
      }

      public Builder clearZlibData() {
        this.bitField0_ = this.bitField0_ & ~0x00000004;
        this.zlibData_ = getDefaultInstance().getZlibData();

        return this;
      }

      @Override
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      @Override
      public Blob getDefaultInstanceForType() {
        return Blob.getDefaultInstance();
      }

      @Override
      public com.google.protobuf.ByteString getLzmaData() {
        return this.lzmaData_;
      }

      @Override
      @java.lang.Deprecated
      public com.google.protobuf.ByteString getOBSOLETEBzip2Data() {
        return this.oBSOLETEBzip2Data_;
      }

      @Override
      public com.google.protobuf.ByteString getRaw() {
        return this.raw_;
      }

      @Override
      public int getRawSize() {
        return this.rawSize_;
      }

      @Override
      public com.google.protobuf.ByteString getZlibData() {
        return this.zlibData_;
      }

      @Override
      public boolean hasLzmaData() {
        return (this.bitField0_ & 0x00000008) == 0x00000008;
      }

      @Override
      @java.lang.Deprecated
      public boolean hasOBSOLETEBzip2Data() {
        return (this.bitField0_ & 0x00000010) == 0x00000010;
      }

      @Override
      public boolean hasRaw() {
        return (this.bitField0_ & 0x00000001) == 0x00000001;
      }

      @Override
      public boolean hasRawSize() {
        return (this.bitField0_ & 0x00000002) == 0x00000002;
      }

      @Override
      public boolean hasZlibData() {
        return (this.bitField0_ & 0x00000004) == 0x00000004;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      private void maybeForceBuilderInitialization() {
      }

      @Override
      public Builder mergeFrom(final Blob other) {
        if (other == Blob.getDefaultInstance()) {
          return this;
        }
        if (other.hasRaw()) {
          setRaw(other.getRaw());
        }
        if (other.hasRawSize()) {
          setRawSize(other.getRawSize());
        }
        if (other.hasZlibData()) {
          setZlibData(other.getZlibData());
        }
        if (other.hasLzmaData()) {
          setLzmaData(other.getLzmaData());
        }
        if (other.hasOBSOLETEBzip2Data()) {
          setOBSOLETEBzip2Data(other.getOBSOLETEBzip2Data());
        }
        return this;
      }

      @Override
      public Builder mergeFrom(
        final com.google.protobuf.CodedInputStream input,
        final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
        while (true) {
          final int tag = input.readTag();
          switch (tag) {
            case 0:

              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {

                return this;
              }
              break;
            }
            case 10: {
              this.bitField0_ |= 0x00000001;
              this.raw_ = input.readBytes();
              break;
            }
            case 16: {
              this.bitField0_ |= 0x00000002;
              this.rawSize_ = input.readInt32();
              break;
            }
            case 26: {
              this.bitField0_ |= 0x00000004;
              this.zlibData_ = input.readBytes();
              break;
            }
            case 34: {
              this.bitField0_ |= 0x00000008;
              this.lzmaData_ = input.readBytes();
              break;
            }
            case 42: {
              this.bitField0_ |= 0x00000010;
              this.oBSOLETEBzip2Data_ = input.readBytes();
              break;
            }
          }
        }
      }

      public Builder setLzmaData(final com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        this.bitField0_ |= 0x00000008;
        this.lzmaData_ = value;

        return this;
      }

      @java.lang.Deprecated
      public Builder setOBSOLETEBzip2Data(
        final com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        this.bitField0_ |= 0x00000010;
        this.oBSOLETEBzip2Data_ = value;

        return this;
      }

      public Builder setRaw(final com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        this.bitField0_ |= 0x00000001;
        this.raw_ = value;

        return this;
      }

      public Builder setRawSize(final int value) {
        this.bitField0_ |= 0x00000002;
        this.rawSize_ = value;

        return this;
      }

      public Builder setZlibData(final com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        this.bitField0_ |= 0x00000004;
        this.zlibData_ = value;

        return this;
      }

      // @@protoc_insertion_point(builder_scope:OSMPBF.Blob)
    }

    public static Blob getDefaultInstance() {
      return defaultInstance;
    }

    public static Builder newBuilder() {
      return Builder.create();
    }

    public static Builder newBuilder(final Blob prototype) {
      return newBuilder().mergeFrom(prototype);
    }

    public static Blob parseDelimitedFrom(final java.io.InputStream input)
      throws java.io.IOException {
      final Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }

    public static Blob parseDelimitedFrom(final java.io.InputStream input,
      final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
      final Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }

    public static Blob parseFrom(final byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }

    public static Blob parseFrom(final byte[] data,
      final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry).buildParsed();
    }

    public static Blob parseFrom(final com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }

    public static Blob parseFrom(final com.google.protobuf.ByteString data,
      final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry).buildParsed();
    }

    public static Blob parseFrom(
      final com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }

    public static Blob parseFrom(
      final com.google.protobuf.CodedInputStream input,
      final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry).buildParsed();
    }

    public static Blob parseFrom(final java.io.InputStream input)
      throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }

    public static Blob parseFrom(final java.io.InputStream input,
      final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry).buildParsed();
    }

    private static final Blob defaultInstance;

    private int bitField0_;

    // optional bytes raw = 1;
    public static final int RAW_FIELD_NUMBER = 1;

    private com.google.protobuf.ByteString raw_;

    // optional int32 raw_size = 2;
    public static final int RAW_SIZE_FIELD_NUMBER = 2;

    private int rawSize_;

    // optional bytes zlib_data = 3;
    public static final int ZLIB_DATA_FIELD_NUMBER = 3;

    private com.google.protobuf.ByteString zlibData_;

    // optional bytes lzma_data = 4;
    public static final int LZMA_DATA_FIELD_NUMBER = 4;

    private com.google.protobuf.ByteString lzmaData_;

    // optional bytes OBSOLETE_bzip2_data = 5 [deprecated = true];
    public static final int OBSOLETE_BZIP2_DATA_FIELD_NUMBER = 5;

    private com.google.protobuf.ByteString oBSOLETEBzip2Data_;

    private byte memoizedIsInitialized = -1;

    private int memoizedSerializedSize = -1;

    private static final long serialVersionUID = 0L;

    static {
      defaultInstance = new Blob(true);
      defaultInstance.initFields();
    }

    private Blob(final boolean noInit) {
    }

    // Use Blob.newBuilder() to construct.
    private Blob(final Builder builder) {
      super(builder);
    }

    @Override
    public Blob getDefaultInstanceForType() {
      return defaultInstance;
    }

    @Override
    public com.google.protobuf.ByteString getLzmaData() {
      return this.lzmaData_;
    }

    @Override
    @java.lang.Deprecated
    public com.google.protobuf.ByteString getOBSOLETEBzip2Data() {
      return this.oBSOLETEBzip2Data_;
    }

    @Override
    public com.google.protobuf.ByteString getRaw() {
      return this.raw_;
    }

    @Override
    public int getRawSize() {
      return this.rawSize_;
    }

    @Override
    public int getSerializedSize() {
      int size = this.memoizedSerializedSize;
      if (size != -1) {
        return size;
      }

      size = 0;
      if ((this.bitField0_ & 0x00000001) == 0x00000001) {
        size += com.google.protobuf.CodedOutputStream.computeBytesSize(1,
          this.raw_);
      }
      if ((this.bitField0_ & 0x00000002) == 0x00000002) {
        size += com.google.protobuf.CodedOutputStream.computeInt32Size(2,
          this.rawSize_);
      }
      if ((this.bitField0_ & 0x00000004) == 0x00000004) {
        size += com.google.protobuf.CodedOutputStream.computeBytesSize(3,
          this.zlibData_);
      }
      if ((this.bitField0_ & 0x00000008) == 0x00000008) {
        size += com.google.protobuf.CodedOutputStream.computeBytesSize(4,
          this.lzmaData_);
      }
      if ((this.bitField0_ & 0x00000010) == 0x00000010) {
        size += com.google.protobuf.CodedOutputStream.computeBytesSize(5,
          this.oBSOLETEBzip2Data_);
      }
      this.memoizedSerializedSize = size;
      return size;
    }

    @Override
    public com.google.protobuf.ByteString getZlibData() {
      return this.zlibData_;
    }

    @Override
    public boolean hasLzmaData() {
      return (this.bitField0_ & 0x00000008) == 0x00000008;
    }

    @Override
    @java.lang.Deprecated
    public boolean hasOBSOLETEBzip2Data() {
      return (this.bitField0_ & 0x00000010) == 0x00000010;
    }

    @Override
    public boolean hasRaw() {
      return (this.bitField0_ & 0x00000001) == 0x00000001;
    }

    @Override
    public boolean hasRawSize() {
      return (this.bitField0_ & 0x00000002) == 0x00000002;
    }

    @Override
    public boolean hasZlibData() {
      return (this.bitField0_ & 0x00000004) == 0x00000004;
    }

    private void initFields() {
      this.raw_ = com.google.protobuf.ByteString.EMPTY;
      this.rawSize_ = 0;
      this.zlibData_ = com.google.protobuf.ByteString.EMPTY;
      this.lzmaData_ = com.google.protobuf.ByteString.EMPTY;
      this.oBSOLETEBzip2Data_ = com.google.protobuf.ByteString.EMPTY;
    }

    @Override
    public final boolean isInitialized() {
      final byte isInitialized = this.memoizedIsInitialized;
      if (isInitialized != -1) {
        return isInitialized == 1;
      }

      this.memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public Builder newBuilderForType() {
      return newBuilder();
    }

    @Override
    public Builder toBuilder() {
      return newBuilder(this);
    }

    @java.lang.Override
    protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    @Override
    public void writeTo(final com.google.protobuf.CodedOutputStream output)
      throws java.io.IOException {
      getSerializedSize();
      if ((this.bitField0_ & 0x00000001) == 0x00000001) {
        output.writeBytes(1, this.raw_);
      }
      if ((this.bitField0_ & 0x00000002) == 0x00000002) {
        output.writeInt32(2, this.rawSize_);
      }
      if ((this.bitField0_ & 0x00000004) == 0x00000004) {
        output.writeBytes(3, this.zlibData_);
      }
      if ((this.bitField0_ & 0x00000008) == 0x00000008) {
        output.writeBytes(4, this.lzmaData_);
      }
      if ((this.bitField0_ & 0x00000010) == 0x00000010) {
        output.writeBytes(5, this.oBSOLETEBzip2Data_);
      }
    }

    // @@protoc_insertion_point(class_scope:OSMPBF.Blob)
  }

  public static final class BlobHeader extends
    com.google.protobuf.GeneratedMessageLite implements BlobHeaderOrBuilder {
    public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<BlobHeader, Builder>
      implements BlobHeaderOrBuilder {
      private static Builder create() {
        return new Builder();
      }

      private int bitField0_;

      // required string type = 1;
      private java.lang.Object type_ = "";

      // optional bytes indexdata = 2;
      private com.google.protobuf.ByteString indexdata_ = com.google.protobuf.ByteString.EMPTY;

      // required int32 datasize = 3;
      private int datasize_;

      // Construct using BlobHeader.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      @Override
      public BlobHeader build() {
        final BlobHeader result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      private BlobHeader buildParsed()
        throws com.google.protobuf.InvalidProtocolBufferException {
        final BlobHeader result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result).asInvalidProtocolBufferException();
        }
        return result;
      }

      @Override
      public BlobHeader buildPartial() {
        final BlobHeader result = new BlobHeader(this);
        final int from_bitField0_ = this.bitField0_;
        int to_bitField0_ = 0;
        if ((from_bitField0_ & 0x00000001) == 0x00000001) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = this.type_;
        if ((from_bitField0_ & 0x00000002) == 0x00000002) {
          to_bitField0_ |= 0x00000002;
        }
        result.indexdata_ = this.indexdata_;
        if ((from_bitField0_ & 0x00000004) == 0x00000004) {
          to_bitField0_ |= 0x00000004;
        }
        result.datasize_ = this.datasize_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      @Override
      public Builder clear() {
        super.clear();
        this.type_ = "";
        this.bitField0_ = this.bitField0_ & ~0x00000001;
        this.indexdata_ = com.google.protobuf.ByteString.EMPTY;
        this.bitField0_ = this.bitField0_ & ~0x00000002;
        this.datasize_ = 0;
        this.bitField0_ = this.bitField0_ & ~0x00000004;
        return this;
      }

      public Builder clearDatasize() {
        this.bitField0_ = this.bitField0_ & ~0x00000004;
        this.datasize_ = 0;

        return this;
      }

      public Builder clearIndexdata() {
        this.bitField0_ = this.bitField0_ & ~0x00000002;
        this.indexdata_ = getDefaultInstance().getIndexdata();

        return this;
      }

      public Builder clearType() {
        this.bitField0_ = this.bitField0_ & ~0x00000001;
        this.type_ = getDefaultInstance().getType();

        return this;
      }

      @Override
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      @Override
      public int getDatasize() {
        return this.datasize_;
      }

      @Override
      public BlobHeader getDefaultInstanceForType() {
        return BlobHeader.getDefaultInstance();
      }

      @Override
      public com.google.protobuf.ByteString getIndexdata() {
        return this.indexdata_;
      }

      @Override
      public String getType() {
        final java.lang.Object ref = this.type_;
        if (!(ref instanceof String)) {
          final String s = ((com.google.protobuf.ByteString)ref).toStringUtf8();
          this.type_ = s;
          return s;
        } else {
          return (String)ref;
        }
      }

      @Override
      public boolean hasDatasize() {
        return (this.bitField0_ & 0x00000004) == 0x00000004;
      }

      @Override
      public boolean hasIndexdata() {
        return (this.bitField0_ & 0x00000002) == 0x00000002;
      }

      @Override
      public boolean hasType() {
        return (this.bitField0_ & 0x00000001) == 0x00000001;
      }

      @Override
      public final boolean isInitialized() {
        if (!hasType()) {

          return false;
        }
        if (!hasDatasize()) {

          return false;
        }
        return true;
      }

      private void maybeForceBuilderInitialization() {
      }

      @Override
      public Builder mergeFrom(final BlobHeader other) {
        if (other == BlobHeader.getDefaultInstance()) {
          return this;
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasIndexdata()) {
          setIndexdata(other.getIndexdata());
        }
        if (other.hasDatasize()) {
          setDatasize(other.getDatasize());
        }
        return this;
      }

      @Override
      public Builder mergeFrom(
        final com.google.protobuf.CodedInputStream input,
        final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
        while (true) {
          final int tag = input.readTag();
          switch (tag) {
            case 0:

              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {

                return this;
              }
              break;
            }
            case 10: {
              this.bitField0_ |= 0x00000001;
              this.type_ = input.readBytes();
              break;
            }
            case 18: {
              this.bitField0_ |= 0x00000002;
              this.indexdata_ = input.readBytes();
              break;
            }
            case 24: {
              this.bitField0_ |= 0x00000004;
              this.datasize_ = input.readInt32();
              break;
            }
          }
        }
      }

      public Builder setDatasize(final int value) {
        this.bitField0_ |= 0x00000004;
        this.datasize_ = value;

        return this;
      }

      public Builder setIndexdata(final com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        this.bitField0_ |= 0x00000002;
        this.indexdata_ = value;

        return this;
      }

      void setType(final com.google.protobuf.ByteString value) {
        this.bitField0_ |= 0x00000001;
        this.type_ = value;

      }

      public Builder setType(final String value) {
        if (value == null) {
          throw new NullPointerException();
        }
        this.bitField0_ |= 0x00000001;
        this.type_ = value;

        return this;
      }

      // @@protoc_insertion_point(builder_scope:OSMPBF.BlobHeader)
    }

    public static BlobHeader getDefaultInstance() {
      return defaultInstance;
    }

    public static Builder newBuilder() {
      return Builder.create();
    }

    public static Builder newBuilder(final BlobHeader prototype) {
      return newBuilder().mergeFrom(prototype);
    }

    public static BlobHeader parseDelimitedFrom(final java.io.InputStream input)
      throws java.io.IOException {
      final Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }

    public static BlobHeader parseDelimitedFrom(
      final java.io.InputStream input,
      final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
      final Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }

    public static BlobHeader parseFrom(final byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }

    public static BlobHeader parseFrom(final byte[] data,
      final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry).buildParsed();
    }

    public static BlobHeader parseFrom(final com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }

    public static BlobHeader parseFrom(
      final com.google.protobuf.ByteString data,
      final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry).buildParsed();
    }

    public static BlobHeader parseFrom(
      final com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }

    public static BlobHeader parseFrom(
      final com.google.protobuf.CodedInputStream input,
      final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry).buildParsed();
    }

    public static BlobHeader parseFrom(final java.io.InputStream input)
      throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }

    public static BlobHeader parseFrom(final java.io.InputStream input,
      final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry).buildParsed();
    }

    private static final BlobHeader defaultInstance;

    private int bitField0_;

    // required string type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;

    private java.lang.Object type_;

    // optional bytes indexdata = 2;
    public static final int INDEXDATA_FIELD_NUMBER = 2;

    private com.google.protobuf.ByteString indexdata_;

    // required int32 datasize = 3;
    public static final int DATASIZE_FIELD_NUMBER = 3;

    private int datasize_;

    private byte memoizedIsInitialized = -1;

    private int memoizedSerializedSize = -1;

    private static final long serialVersionUID = 0L;

    static {
      defaultInstance = new BlobHeader(true);
      defaultInstance.initFields();
    }

    private BlobHeader(final boolean noInit) {
    }

    // Use BlobHeader.newBuilder() to construct.
    private BlobHeader(final Builder builder) {
      super(builder);
    }

    @Override
    public int getDatasize() {
      return this.datasize_;
    }

    @Override
    public BlobHeader getDefaultInstanceForType() {
      return defaultInstance;
    }

    @Override
    public com.google.protobuf.ByteString getIndexdata() {
      return this.indexdata_;
    }

    @Override
    public int getSerializedSize() {
      int size = this.memoizedSerializedSize;
      if (size != -1) {
        return size;
      }

      size = 0;
      if ((this.bitField0_ & 0x00000001) == 0x00000001) {
        size += com.google.protobuf.CodedOutputStream.computeBytesSize(1,
          getTypeBytes());
      }
      if ((this.bitField0_ & 0x00000002) == 0x00000002) {
        size += com.google.protobuf.CodedOutputStream.computeBytesSize(2,
          this.indexdata_);
      }
      if ((this.bitField0_ & 0x00000004) == 0x00000004) {
        size += com.google.protobuf.CodedOutputStream.computeInt32Size(3,
          this.datasize_);
      }
      this.memoizedSerializedSize = size;
      return size;
    }

    @Override
    public String getType() {
      final java.lang.Object ref = this.type_;
      if (ref instanceof String) {
        return (String)ref;
      } else {
        final com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString)ref;
        final String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          this.type_ = s;
        }
        return s;
      }
    }

    private com.google.protobuf.ByteString getTypeBytes() {
      final java.lang.Object ref = this.type_;
      if (ref instanceof String) {
        final com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String)ref);
        this.type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString)ref;
      }
    }

    @Override
    public boolean hasDatasize() {
      return (this.bitField0_ & 0x00000004) == 0x00000004;
    }

    @Override
    public boolean hasIndexdata() {
      return (this.bitField0_ & 0x00000002) == 0x00000002;
    }

    @Override
    public boolean hasType() {
      return (this.bitField0_ & 0x00000001) == 0x00000001;
    }

    private void initFields() {
      this.type_ = "";
      this.indexdata_ = com.google.protobuf.ByteString.EMPTY;
      this.datasize_ = 0;
    }

    @Override
    public final boolean isInitialized() {
      final byte isInitialized = this.memoizedIsInitialized;
      if (isInitialized != -1) {
        return isInitialized == 1;
      }

      if (!hasType()) {
        this.memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDatasize()) {
        this.memoizedIsInitialized = 0;
        return false;
      }
      this.memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public Builder newBuilderForType() {
      return newBuilder();
    }

    @Override
    public Builder toBuilder() {
      return newBuilder(this);
    }

    @java.lang.Override
    protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    @Override
    public void writeTo(final com.google.protobuf.CodedOutputStream output)
      throws java.io.IOException {
      getSerializedSize();
      if ((this.bitField0_ & 0x00000001) == 0x00000001) {
        output.writeBytes(1, getTypeBytes());
      }
      if ((this.bitField0_ & 0x00000002) == 0x00000002) {
        output.writeBytes(2, this.indexdata_);
      }
      if ((this.bitField0_ & 0x00000004) == 0x00000004) {
        output.writeInt32(3, this.datasize_);
      }
    }

    // @@protoc_insertion_point(class_scope:OSMPBF.BlobHeader)
  }

  public interface BlobHeaderOrBuilder extends
    com.google.protobuf.MessageLiteOrBuilder {

    int getDatasize();

    com.google.protobuf.ByteString getIndexdata();

    String getType();

    // required int32 datasize = 3;
    boolean hasDatasize();

    // optional bytes indexdata = 2;
    boolean hasIndexdata();

    // required string type = 1;
    boolean hasType();
  }

  public interface BlobOrBuilder extends
    com.google.protobuf.MessageLiteOrBuilder {

    com.google.protobuf.ByteString getLzmaData();

    @java.lang.Deprecated
    com.google.protobuf.ByteString getOBSOLETEBzip2Data();

    com.google.protobuf.ByteString getRaw();

    int getRawSize();

    com.google.protobuf.ByteString getZlibData();

    // optional bytes lzma_data = 4;
    boolean hasLzmaData();

    // optional bytes OBSOLETE_bzip2_data = 5 [deprecated = true];
    @java.lang.Deprecated
    boolean hasOBSOLETEBzip2Data();

    // optional bytes raw = 1;
    boolean hasRaw();

    // optional int32 raw_size = 2;
    boolean hasRawSize();

    // optional bytes zlib_data = 3;
    boolean hasZlibData();
  }

  public static void registerAllExtensions(
    final com.google.protobuf.ExtensionRegistryLite registry) {
  }

  static {
  }

  private Fileformat() {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
