/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.revolsys.gis.esri.gdb.file.capi.swig;

public class Envelope {
  protected static long getCPtr(final Envelope obj) {
    return obj == null ? 0 : obj.swigCPtr;
  }

  protected boolean swigCMemOwn;

  private long swigCPtr;

  public Envelope() {
    this(EsriFileGdbJNI.new_Envelope__SWIG_0(), true);
  }

  public Envelope(final double xmin, final double xmax, final double ymin, final double ymax) {
    this(EsriFileGdbJNI.new_Envelope__SWIG_1(xmin, xmax, ymin, ymax), true);
  }

  protected Envelope(final long cPtr, final boolean cMemoryOwn) {
    this.swigCMemOwn = cMemoryOwn;
    this.swigCPtr = cPtr;
  }

  public synchronized void delete() {
    if (this.swigCPtr != 0) {
      if (this.swigCMemOwn) {
        this.swigCMemOwn = false;
        EsriFileGdbJNI.delete_Envelope(this.swigCPtr);
      }
      this.swigCPtr = 0;
    }
  }

  @Override
  protected void finalize() {
    delete();
  }

  public double getXMax() {
    return EsriFileGdbJNI.Envelope_xMax_get(this.swigCPtr, this);
  }

  public double getXMin() {
    return EsriFileGdbJNI.Envelope_xMin_get(this.swigCPtr, this);
  }

  public double getYMax() {
    return EsriFileGdbJNI.Envelope_yMax_get(this.swigCPtr, this);
  }

  public double getYMin() {
    return EsriFileGdbJNI.Envelope_yMin_get(this.swigCPtr, this);
  }

  public double getZMax() {
    return EsriFileGdbJNI.Envelope_zMax_get(this.swigCPtr, this);
  }

  public double getZMin() {
    return EsriFileGdbJNI.Envelope_zMin_get(this.swigCPtr, this);
  }

  public boolean IsEmpty() {
    return EsriFileGdbJNI.Envelope_IsEmpty(this.swigCPtr, this);
  }

  public void SetEmpty() {
    EsriFileGdbJNI.Envelope_SetEmpty(this.swigCPtr, this);
  }

  public void setXMax(final double value) {
    EsriFileGdbJNI.Envelope_xMax_set(this.swigCPtr, this, value);
  }

  public void setXMin(final double value) {
    EsriFileGdbJNI.Envelope_xMin_set(this.swigCPtr, this, value);
  }

  public void setYMax(final double value) {
    EsriFileGdbJNI.Envelope_yMax_set(this.swigCPtr, this, value);
  }

  public void setYMin(final double value) {
    EsriFileGdbJNI.Envelope_yMin_set(this.swigCPtr, this, value);
  }

  public void setZMax(final double value) {
    EsriFileGdbJNI.Envelope_zMax_set(this.swigCPtr, this, value);
  }

  public void setZMin(final double value) {
    EsriFileGdbJNI.Envelope_zMin_set(this.swigCPtr, this, value);
  }

}
