/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.revolsys.gis.esri.gdb.file.capi.swig;

public class VectorOfString {
  protected static long getCPtr(final VectorOfString obj) {
    return obj == null ? 0 : obj.swigCPtr;
  }

  private transient long swigCPtr;

  protected transient boolean swigCMemOwn;

  public VectorOfString() {
    this(EsriFileGdbJNI.new_VectorOfString__SWIG_0(), true);
  }

  public VectorOfString(final long n) {
    this(EsriFileGdbJNI.new_VectorOfString__SWIG_1(n), true);
  }

  protected VectorOfString(final long cPtr, final boolean cMemoryOwn) {
    this.swigCMemOwn = cMemoryOwn;
    this.swigCPtr = cPtr;
  }

  public void add(final String x) {
    EsriFileGdbJNI.VectorOfString_add(this.swigCPtr, this, x);
  }

  public long capacity() {
    return EsriFileGdbJNI.VectorOfString_capacity(this.swigCPtr, this);
  }

  public void clear() {
    EsriFileGdbJNI.VectorOfString_clear(this.swigCPtr, this);
  }

  public synchronized void delete() {
    if (this.swigCPtr != 0) {
      if (this.swigCMemOwn) {
        this.swigCMemOwn = false;
        EsriFileGdbJNI.delete_VectorOfString(this.swigCPtr);
      }
      this.swigCPtr = 0;
    }
  }

  @Override
  protected void finalize() {
    delete();
  }

  public String get(final int i) {
    return EsriFileGdbJNI.VectorOfString_get(this.swigCPtr, this, i);
  }

  public boolean isEmpty() {
    return EsriFileGdbJNI.VectorOfString_isEmpty(this.swigCPtr, this);
  }

  public void reserve(final long n) {
    EsriFileGdbJNI.VectorOfString_reserve(this.swigCPtr, this, n);
  }

  public void set(final int i, final String val) {
    EsriFileGdbJNI.VectorOfString_set(this.swigCPtr, this, i, val);
  }

  public long size() {
    return EsriFileGdbJNI.VectorOfString_size(this.swigCPtr, this);
  }

}
