/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.revolsys.gis.esri.gdb.file.capi.swig;

public class VectorOfFieldDef {
  protected static long getCPtr(final VectorOfFieldDef obj) {
    return obj == null ? 0 : obj.swigCPtr;
  }

  protected boolean swigCMemOwn;

  private long swigCPtr;

  public VectorOfFieldDef() {
    this(EsriFileGdbJNI.new_VectorOfFieldDef__SWIG_0(), true);
  }

  public VectorOfFieldDef(final long n) {
    this(EsriFileGdbJNI.new_VectorOfFieldDef__SWIG_1(n), true);
  }

  protected VectorOfFieldDef(final long cPtr, final boolean cMemoryOwn) {
    this.swigCMemOwn = cMemoryOwn;
    this.swigCPtr = cPtr;
  }

  public void add(final FieldDef x) {
    EsriFileGdbJNI.VectorOfFieldDef_add(this.swigCPtr, this, FieldDef.getCPtr(x), x);
  }

  public long capacity() {
    return EsriFileGdbJNI.VectorOfFieldDef_capacity(this.swigCPtr, this);
  }

  public void clear() {
    EsriFileGdbJNI.VectorOfFieldDef_clear(this.swigCPtr, this);
  }

  public synchronized void delete() {
    if (this.swigCPtr != 0) {
      if (this.swigCMemOwn) {
        this.swigCMemOwn = false;
        EsriFileGdbJNI.delete_VectorOfFieldDef(this.swigCPtr);
      }
      this.swigCPtr = 0;
    }
  }

  @Override
  protected void finalize() {
    delete();
  }

  public FieldDef get(final int i) {
    return new FieldDef(EsriFileGdbJNI.VectorOfFieldDef_get(this.swigCPtr, this, i), false);
  }

  public boolean isEmpty() {
    return EsriFileGdbJNI.VectorOfFieldDef_isEmpty(this.swigCPtr, this);
  }

  public void reserve(final long n) {
    EsriFileGdbJNI.VectorOfFieldDef_reserve(this.swigCPtr, this, n);
  }

  public void set(final int i, final FieldDef val) {
    EsriFileGdbJNI.VectorOfFieldDef_set(this.swigCPtr, this, i, FieldDef.getCPtr(val), val);
  }

  public long size() {
    return EsriFileGdbJNI.VectorOfFieldDef_size(this.swigCPtr, this);
  }

}
