/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.revolsys.gis.esri.gdb.file.swig;

public class DoubleArrayValue {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected DoubleArrayValue(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DoubleArrayValue obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        EsriFileGdbJNI.delete_DoubleArrayValue(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public DoubleArrayValue() {
    this(EsriFileGdbJNI.new_DoubleArrayValue(), true);
  }

  public double get(int i) {
    return EsriFileGdbJNI.DoubleArrayValue_get(swigCPtr, this, i);
  }

  public void set(int i, double value) {
    EsriFileGdbJNI.DoubleArrayValue_set(swigCPtr, this, i, value);
  }

}
