/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.revolsys.gis.esri.gdb.file.swig;

public class EnumSpatialReferenceInfo {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected EnumSpatialReferenceInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EnumSpatialReferenceInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        EsriFileGdbJNI.delete_EnumSpatialReferenceInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public EnumSpatialReferenceInfo() {
    this(EsriFileGdbJNI.new_EnumSpatialReferenceInfo(), true);
  }

  public boolean NextGeographicSpatialReference(SpatialReferenceInfo spatialReferenceInfo) {
    return EsriFileGdbJNI.EnumSpatialReferenceInfo_NextGeographicSpatialReference(swigCPtr, this, SpatialReferenceInfo.getCPtr(spatialReferenceInfo), spatialReferenceInfo);
  }

  public boolean NextProjectedSpatialReference(SpatialReferenceInfo spatialReferenceInfo) {
    return EsriFileGdbJNI.EnumSpatialReferenceInfo_NextProjectedSpatialReference(swigCPtr, this, SpatialReferenceInfo.getCPtr(spatialReferenceInfo), spatialReferenceInfo);
  }

  public void Reset() {
    EsriFileGdbJNI.EnumSpatialReferenceInfo_Reset(swigCPtr, this);
  }

}
