/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.revolsys.gis.esri.gdb.file.swig;

public class ErrorRecord {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ErrorRecord(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ErrorRecord obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        EsriFileGdbJNI.delete_ErrorRecord(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setErrorNumber(int value) {
    EsriFileGdbJNI.ErrorRecord_errorNumber_set(swigCPtr, this, value);
  }

  public int getErrorNumber() {
    return EsriFileGdbJNI.ErrorRecord_errorNumber_get(swigCPtr, this);
  }

  public void setErrorDescription(String value) {
    EsriFileGdbJNI.ErrorRecord_errorDescription_set(swigCPtr, this, value);
  }

  public String getErrorDescription() {
    return EsriFileGdbJNI.ErrorRecord_errorDescription_get(swigCPtr, this);
  }

  public ErrorRecord() {
    this(EsriFileGdbJNI.new_ErrorRecord(), true);
  }

}
