/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.revolsys.gis.esri.gdb.file.swig;

public class FieldTypeValue {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected FieldTypeValue(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FieldTypeValue obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        EsriFileGdbJNI.delete_FieldTypeValue(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setValue(FieldType value) {
    EsriFileGdbJNI.FieldTypeValue_value_set(swigCPtr, this, value.swigValue());
  }

  public FieldType getValue() {
    return FieldType.swigToEnum(EsriFileGdbJNI.FieldTypeValue_value_get(swigCPtr, this));
  }

  public FieldTypeValue() {
    this(EsriFileGdbJNI.new_FieldTypeValue(), true);
  }

}
