/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.revolsys.gis.esri.gdb.file.swig;

public class FloatArray {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected FloatArray(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FloatArray obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      EsriFileGdbJNI.delete_FloatArray(swigCPtr);
    }
    swigCPtr = 0;
  }

  public FloatArray() {
    this(EsriFileGdbJNI.new_FloatArray(), true);
  }

  public float get(int i) {
    return EsriFileGdbJNI.FloatArray_get(swigCPtr, this, i);
  }

  public void set(int i, float value) {
    EsriFileGdbJNI.FloatArray_set(swigCPtr, this, i, value);
  }

}
