/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.revolsys.gis.esri.gdb.file.swig;

public class FloatValue {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected FloatValue(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FloatValue obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        EsriFileGdbJNI.delete_FloatValue(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setValue(float value) {
    EsriFileGdbJNI.FloatValue_value_set(swigCPtr, this, value);
  }

  public float getValue() {
    return EsriFileGdbJNI.FloatValue_value_get(swigCPtr, this);
  }

  public FloatValue() {
    this(EsriFileGdbJNI.new_FloatValue(), true);
  }

}
