/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.revolsys.gis.esri.gdb.file.swig;

public class FloatArray {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected FloatArray(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FloatArray obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        EsriFileGdbJNI.delete_FloatArray(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public FloatArray(int nelements) {
    this(EsriFileGdbJNI.new_FloatArray(nelements), true);
  }

  public float getitem(int index) {
    return EsriFileGdbJNI.FloatArray_getitem(swigCPtr, this, index);
  }

  public void setitem(int index, float value) {
    EsriFileGdbJNI.FloatArray_setitem(swigCPtr, this, index, value);
  }

  public SWIGTYPE_p_float cast() {
    long cPtr = EsriFileGdbJNI.FloatArray_cast(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_float(cPtr, false);
  }

  public static FloatArray frompointer(SWIGTYPE_p_float t) {
    long cPtr = EsriFileGdbJNI.FloatArray_frompointer(SWIGTYPE_p_float.getCPtr(t));
    return (cPtr == 0) ? null : new FloatArray(cPtr, false);
  }

}
