/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.revolsys.gis.esri.gdb.file.swig;

public class Geodatabase {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Geodatabase(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Geodatabase obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        EsriFileGdbJNI.delete_Geodatabase(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public int GetDatasetTypes(SWIGTYPE_p_std__vectorT_std__wstring_t datasetTypes) {
    return EsriFileGdbJNI.Geodatabase_GetDatasetTypes(swigCPtr, this, SWIGTYPE_p_std__vectorT_std__wstring_t.getCPtr(datasetTypes));
  }

  public int GetDatasetRelationshipTypes(SWIGTYPE_p_std__vectorT_std__wstring_t relationshipTypes) {
    return EsriFileGdbJNI.Geodatabase_GetDatasetRelationshipTypes(swigCPtr, this, SWIGTYPE_p_std__vectorT_std__wstring_t.getCPtr(relationshipTypes));
  }

  public int GetChildDatasets(String parentPath, String datasetType, SWIGTYPE_p_std__vectorT_std__wstring_t childDatasets) {
    return EsriFileGdbJNI.Geodatabase_GetChildDatasets(swigCPtr, this, parentPath, datasetType, SWIGTYPE_p_std__vectorT_std__wstring_t.getCPtr(childDatasets));
  }

  public int GetRelatedDatasets(String path, String relType, String datasetType, SWIGTYPE_p_std__vectorT_std__wstring_t relatedDatasets) {
    return EsriFileGdbJNI.Geodatabase_GetRelatedDatasets(swigCPtr, this, path, relType, datasetType, SWIGTYPE_p_std__vectorT_std__wstring_t.getCPtr(relatedDatasets));
  }

  public int GetDatasetDefinition(String path, String datasetType, StringValue datasetDef) {
    return EsriFileGdbJNI.Geodatabase_GetDatasetDefinition(swigCPtr, this, path, datasetType, datasetDef);
  }

  public int GetChildDatasetDefinitions(String parentPath, String datasetType, SWIGTYPE_p_std__vectorT_std__string_t childDatasetDefs) {
    return EsriFileGdbJNI.Geodatabase_GetChildDatasetDefinitions(swigCPtr, this, parentPath, datasetType, SWIGTYPE_p_std__vectorT_std__string_t.getCPtr(childDatasetDefs));
  }

  public int GetRelatedDatasetDefinitions(String path, String relType, String datasetType, SWIGTYPE_p_std__vectorT_std__string_t relatedDatasetDefs) {
    return EsriFileGdbJNI.Geodatabase_GetRelatedDatasetDefinitions(swigCPtr, this, path, relType, datasetType, SWIGTYPE_p_std__vectorT_std__string_t.getCPtr(relatedDatasetDefs));
  }

  public int GetDatasetDocumentation(String path, String datasetType, StringValue documentation) {
    return EsriFileGdbJNI.Geodatabase_GetDatasetDocumentation(swigCPtr, this, path, datasetType, documentation);
  }

  public int CreateFeatureDataset(String featureDatasetDef) {
    return EsriFileGdbJNI.Geodatabase_CreateFeatureDataset(swigCPtr, this, featureDatasetDef);
  }

  public int CreateTable(String tableDef, String parent, Table table) {
    return EsriFileGdbJNI.Geodatabase_CreateTable(swigCPtr, this, tableDef, parent, Table.getCPtr(table), table);
  }

  public int OpenTable(String path, Table table) {
    return EsriFileGdbJNI.Geodatabase_OpenTable(swigCPtr, this, path, Table.getCPtr(table), table);
  }

  public int CloseTable(Table table) {
    return EsriFileGdbJNI.Geodatabase_CloseTable(swigCPtr, this, Table.getCPtr(table), table);
  }

  public int Rename(String path, String datasetType, String newName) {
    return EsriFileGdbJNI.Geodatabase_Rename(swigCPtr, this, path, datasetType, newName);
  }

  public int Move(String path, String newParentPath) {
    return EsriFileGdbJNI.Geodatabase_Move(swigCPtr, this, path, newParentPath);
  }

  public int Delete(String path, String datasetType) {
    return EsriFileGdbJNI.Geodatabase_Delete(swigCPtr, this, path, datasetType);
  }

  public int GetDomains(SWIGTYPE_p_std__vectorT_std__wstring_t domainNames) {
    return EsriFileGdbJNI.Geodatabase_GetDomains(swigCPtr, this, SWIGTYPE_p_std__vectorT_std__wstring_t.getCPtr(domainNames));
  }

  public int CreateDomain(String domainDef) {
    return EsriFileGdbJNI.Geodatabase_CreateDomain(swigCPtr, this, domainDef);
  }

  public int AlterDomain(String domainDef) {
    return EsriFileGdbJNI.Geodatabase_AlterDomain(swigCPtr, this, domainDef);
  }

  public int DeleteDomain(String domainName) {
    return EsriFileGdbJNI.Geodatabase_DeleteDomain(swigCPtr, this, domainName);
  }

  public int GetDomainDefinition(String domainName, StringValue domainDef) {
    return EsriFileGdbJNI.Geodatabase_GetDomainDefinition(swigCPtr, this, domainName, domainDef);
  }

  public int GetQueryName(String path, WstringValue queryName) {
    return EsriFileGdbJNI.Geodatabase_GetQueryName(swigCPtr, this, path, queryName);
  }

  public int ExecuteSQL(String sqlStmt, boolean recycling, EnumRows rows) {
    return EsriFileGdbJNI.Geodatabase_ExecuteSQL(swigCPtr, this, sqlStmt, recycling, EnumRows.getCPtr(rows), rows);
  }

  public Geodatabase() {
    this(EsriFileGdbJNI.new_Geodatabase(), true);
  }

}
