/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.revolsys.gis.esri.gdb.file.swig;

public class IntArrayValue {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected IntArrayValue(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IntArrayValue obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        EsriFileGdbJNI.delete_IntArrayValue(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public IntArrayValue() {
    this(EsriFileGdbJNI.new_IntArrayValue(), true);
  }

  public int get(int i) {
    return EsriFileGdbJNI.IntArrayValue_get(swigCPtr, this, i);
  }

  public void set(int i, int value) {
    EsriFileGdbJNI.IntArrayValue_set(swigCPtr, this, i, value);
  }

}
