/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.revolsys.gis.esri.gdb.file.swig;

public class Material {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Material(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Material obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        EsriFileGdbJNI.delete_Material(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCount(int value) {
    EsriFileGdbJNI.Material_count_set(swigCPtr, this, value);
  }

  public int getCount() {
    return EsriFileGdbJNI.Material_count_get(swigCPtr, this);
  }

  public void setCompressionType(int value) {
    EsriFileGdbJNI.Material_compressionType_set(swigCPtr, this, value);
  }

  public int getCompressionType() {
    return EsriFileGdbJNI.Material_compressionType_get(swigCPtr, this);
  }

  public IntArray getParts() {
  return new IntArray(EsriFileGdbJNI.Material_getParts(swigCPtr, this), false);
}

  public UnsignedCharArray getMaterials() {
  return new UnsignedCharArray(EsriFileGdbJNI.Material_getMaterials(swigCPtr, this), false);
}

  public Material() {
    this(EsriFileGdbJNI.new_Material(), true);
  }

}
