/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.revolsys.gis.esri.gdb.file.swig;

public class MultiPatchShapeBuffer extends ShapeBuffer {
  private long swigCPtr;

  protected MultiPatchShapeBuffer(long cPtr, boolean cMemoryOwn) {
    super(EsriFileGdbJNI.SWIGMultiPatchShapeBufferUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MultiPatchShapeBuffer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        EsriFileGdbJNI.delete_MultiPatchShapeBuffer(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public int GetExtent(DoubleArrayValue extent) {
    return EsriFileGdbJNI.MultiPatchShapeBuffer_GetExtent(swigCPtr, this, extent);
  }

  public int GetNumParts(IntValue numParts) {
    return EsriFileGdbJNI.MultiPatchShapeBuffer_GetNumParts(swigCPtr, this, numParts);
  }

  public int GetNumPoints(IntValue numPoints) {
    return EsriFileGdbJNI.MultiPatchShapeBuffer_GetNumPoints(swigCPtr, this, numPoints);
  }

  public int GetParts(IntArrayValue parts) {
    return EsriFileGdbJNI.MultiPatchShapeBuffer_GetParts(swigCPtr, this, parts);
  }

  public int GetPartDescriptors(IntArrayValue partDescriptorArray) {
    return EsriFileGdbJNI.MultiPatchShapeBuffer_GetPartDescriptors(swigCPtr, this, partDescriptorArray);
  }

  public int GetPoints(PointArrayValue points) {
    return EsriFileGdbJNI.MultiPatchShapeBuffer_GetPoints(swigCPtr, this, points);
  }

  public int GetZExtent(DoubleArrayValue zExtent) {
    return EsriFileGdbJNI.MultiPatchShapeBuffer_GetZExtent(swigCPtr, this, zExtent);
  }

  public int GetZs(DoubleArrayValue zArray) {
    return EsriFileGdbJNI.MultiPatchShapeBuffer_GetZs(swigCPtr, this, zArray);
  }

  public int GetMExtent(DoubleArrayValue mExtent) {
    return EsriFileGdbJNI.MultiPatchShapeBuffer_GetMExtent(swigCPtr, this, mExtent);
  }

  public int GetMs(DoubleArrayValue mArray) {
    return EsriFileGdbJNI.MultiPatchShapeBuffer_GetMs(swigCPtr, this, mArray);
  }

  public int GetIDs(IntArrayValue ids) {
    return EsriFileGdbJNI.MultiPatchShapeBuffer_GetIDs(swigCPtr, this, ids);
  }

  public int GetMaterials(IntValue numMaterials, IntValue compressionType, IntArrayValue materialParts, UnsignedCharArrayValue materials) {
    return EsriFileGdbJNI.MultiPatchShapeBuffer_GetMaterials(swigCPtr, this, numMaterials, compressionType, materialParts, materials);
  }

  public int Setup(ShapeType shapeType, int numParts, int numPoints, int numTextures, int textureDimension, int numMaterials) {
    return EsriFileGdbJNI.MultiPatchShapeBuffer_Setup__SWIG_0(swigCPtr, this, shapeType.swigValue(), numParts, numPoints, numTextures, textureDimension, numMaterials);
  }

  public int Setup(ShapeType shapeType, int numParts, int numPoints, int numTextures, int textureDimension) {
    return EsriFileGdbJNI.MultiPatchShapeBuffer_Setup__SWIG_1(swigCPtr, this, shapeType.swigValue(), numParts, numPoints, numTextures, textureDimension);
  }

  public int Setup(ShapeType shapeType, int numParts, int numPoints, int numTextures) {
    return EsriFileGdbJNI.MultiPatchShapeBuffer_Setup__SWIG_2(swigCPtr, this, shapeType.swigValue(), numParts, numPoints, numTextures);
  }

  public int Setup(ShapeType shapeType, int numParts, int numPoints) {
    return EsriFileGdbJNI.MultiPatchShapeBuffer_Setup__SWIG_3(swigCPtr, this, shapeType.swigValue(), numParts, numPoints);
  }

  public int CalculateExtent() {
    return EsriFileGdbJNI.MultiPatchShapeBuffer_CalculateExtent(swigCPtr, this);
  }

  public FloatArray getNormals() {
  return new FloatArray(EsriFileGdbJNI.MultiPatchShapeBuffer_getNormals(swigCPtr, this), false);
}

  public MultiPatchShapeBuffer() {
    this(EsriFileGdbJNI.new_MultiPatchShapeBuffer(), true);
  }

}
