/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.revolsys.gis.esri.gdb.file.swig;

public class MultiPatchShapeBuffer extends ShapeBuffer {
  private long swigCPtr;

  protected MultiPatchShapeBuffer(long cPtr, boolean cMemoryOwn) {
    super(EsriFileGdbJNI.SWIGMultiPatchShapeBufferUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MultiPatchShapeBuffer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        EsriFileGdbJNI.delete_MultiPatchShapeBuffer(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public int Setup(ShapeType shapeType, int numParts, int numPoints, int numTextures, int textureDimension, int numMaterials) {
    return EsriFileGdbJNI.MultiPatchShapeBuffer_Setup__SWIG_0(swigCPtr, this, shapeType.swigValue(), numParts, numPoints, numTextures, textureDimension, numMaterials);
  }

  public int Setup(ShapeType shapeType, int numParts, int numPoints, int numTextures, int textureDimension) {
    return EsriFileGdbJNI.MultiPatchShapeBuffer_Setup__SWIG_1(swigCPtr, this, shapeType.swigValue(), numParts, numPoints, numTextures, textureDimension);
  }

  public int Setup(ShapeType shapeType, int numParts, int numPoints, int numTextures) {
    return EsriFileGdbJNI.MultiPatchShapeBuffer_Setup__SWIG_2(swigCPtr, this, shapeType.swigValue(), numParts, numPoints, numTextures);
  }

  public int Setup(ShapeType shapeType, int numParts, int numPoints) {
    return EsriFileGdbJNI.MultiPatchShapeBuffer_Setup__SWIG_3(swigCPtr, this, shapeType.swigValue(), numParts, numPoints);
  }

  public int CalculateExtent() {
    return EsriFileGdbJNI.MultiPatchShapeBuffer_CalculateExtent(swigCPtr, this);
  }

  public PointArray getPoints() {
  return new PointArray(EsriFileGdbJNI.MultiPatchShapeBuffer_getPoints(swigCPtr, this), false);
}

  public FloatArray getNormals() {
  return new FloatArray(EsriFileGdbJNI.MultiPatchShapeBuffer_getNormals(swigCPtr, this), false);
}

  public DoubleArray getExtent() {
  return new DoubleArray(EsriFileGdbJNI.MultiPatchShapeBuffer_getExtent(swigCPtr, this), false);
}

  public DoubleArray getMExtent() {
  return new DoubleArray(EsriFileGdbJNI.MultiPatchShapeBuffer_getMExtent(swigCPtr, this), false);
}

  public DoubleArray getZExtent() {
  return new DoubleArray(EsriFileGdbJNI.MultiPatchShapeBuffer_getZExtent(swigCPtr, this), false);
}

  public DoubleArray getZs() {
  return new DoubleArray(EsriFileGdbJNI.MultiPatchShapeBuffer_getZs(swigCPtr, this), false);
}

  public DoubleArray getMs() {
  return new DoubleArray(EsriFileGdbJNI.MultiPatchShapeBuffer_getMs(swigCPtr, this), false);
}

  public IntArray getIDs() {
  return new IntArray(EsriFileGdbJNI.MultiPatchShapeBuffer_getIDs(swigCPtr, this), false);
}

  public IntArray getParts() {
  return new IntArray(EsriFileGdbJNI.MultiPatchShapeBuffer_getParts(swigCPtr, this), false);
}

  public IntArray getPartDescriptors() {
  return new IntArray(EsriFileGdbJNI.MultiPatchShapeBuffer_getPartDescriptors(swigCPtr, this), false);
}

  public int getNumPoints() {
    return EsriFileGdbJNI.MultiPatchShapeBuffer_getNumPoints(swigCPtr, this);
  }

  public int getNumParts() {
    return EsriFileGdbJNI.MultiPatchShapeBuffer_getNumParts(swigCPtr, this);
  }

  public MultiPatchShapeBuffer() {
    this(EsriFileGdbJNI.new_MultiPatchShapeBuffer(), true);
  }

}
