/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.revolsys.gis.esri.gdb.file.swig;

public class MultiPointShapeBuffer extends ShapeBuffer {
  private long swigCPtr;

  protected MultiPointShapeBuffer(long cPtr, boolean cMemoryOwn) {
    super(EsriFileGdbJNI.SWIGMultiPointShapeBufferUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MultiPointShapeBuffer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        EsriFileGdbJNI.delete_MultiPointShapeBuffer(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public int Setup(ShapeType shapeType, int numPoints) {
    return EsriFileGdbJNI.MultiPointShapeBuffer_Setup(swigCPtr, this, shapeType.swigValue(), numPoints);
  }

  public int CalculateExtent() {
    return EsriFileGdbJNI.MultiPointShapeBuffer_CalculateExtent(swigCPtr, this);
  }

  public DoubleArray getExtent() {
  return new DoubleArray(EsriFileGdbJNI.MultiPointShapeBuffer_getExtent(swigCPtr, this), false);
}

  public DoubleArray getMExtent() {
  return new DoubleArray(EsriFileGdbJNI.MultiPointShapeBuffer_getMExtent(swigCPtr, this), false);
}

  public DoubleArray getZExtent() {
  return new DoubleArray(EsriFileGdbJNI.MultiPointShapeBuffer_getZExtent(swigCPtr, this), false);
}

  public DoubleArray getZs() {
  return new DoubleArray(EsriFileGdbJNI.MultiPointShapeBuffer_getZs(swigCPtr, this), false);
}

  public DoubleArray getMs() {
  return new DoubleArray(EsriFileGdbJNI.MultiPointShapeBuffer_getMs(swigCPtr, this), false);
}

  public IntArray getIDs() {
  return new IntArray(EsriFileGdbJNI.MultiPointShapeBuffer_getIDs(swigCPtr, this), false);
}

  public int getNumPoints() {
    return EsriFileGdbJNI.MultiPointShapeBuffer_getNumPoints(swigCPtr, this);
  }

  public PointArray getPoints() {
  return new PointArray(EsriFileGdbJNI.MultiPointShapeBuffer_getPoints(swigCPtr, this), false);
}

  public MultiPointShapeBuffer() {
    this(EsriFileGdbJNI.new_MultiPointShapeBuffer(), true);
  }

}
