/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.revolsys.gis.esri.gdb.file.swig;

public class MultiPartShapeBuffer extends ShapeBuffer {
  private long swigCPtr;

  protected MultiPartShapeBuffer(long cPtr, boolean cMemoryOwn) {
    super(EsriFileGdbJNI.SWIGMultiPartShapeBufferUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MultiPartShapeBuffer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        EsriFileGdbJNI.delete_MultiPartShapeBuffer(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public int GetExtent(SWIGTYPE_p_double extent) {
    return EsriFileGdbJNI.MultiPartShapeBuffer_GetExtent(swigCPtr, this, SWIGTYPE_p_double.getCPtr(extent));
  }

  public int GetNumParts(SWIGTYPE_p_int numParts) {
    return EsriFileGdbJNI.MultiPartShapeBuffer_GetNumParts(swigCPtr, this, SWIGTYPE_p_int.getCPtr(numParts));
  }

  public int GetNumPoints(SWIGTYPE_p_int numPoints) {
    return EsriFileGdbJNI.MultiPartShapeBuffer_GetNumPoints(swigCPtr, this, SWIGTYPE_p_int.getCPtr(numPoints));
  }

  public int GetParts(SWIGTYPE_p_int parts) {
    return EsriFileGdbJNI.MultiPartShapeBuffer_GetParts(swigCPtr, this, SWIGTYPE_p_int.getCPtr(parts));
  }

  public int GetPoints(Point points) {
    return EsriFileGdbJNI.MultiPartShapeBuffer_GetPoints(swigCPtr, this, Point.getCPtr(points), points);
  }

  public int GetZExtent(SWIGTYPE_p_double zExtent) {
    return EsriFileGdbJNI.MultiPartShapeBuffer_GetZExtent(swigCPtr, this, SWIGTYPE_p_double.getCPtr(zExtent));
  }

  public int GetZs(SWIGTYPE_p_double zArray) {
    return EsriFileGdbJNI.MultiPartShapeBuffer_GetZs(swigCPtr, this, SWIGTYPE_p_double.getCPtr(zArray));
  }

  public int GetMExtent(SWIGTYPE_p_double mExtent) {
    return EsriFileGdbJNI.MultiPartShapeBuffer_GetMExtent(swigCPtr, this, SWIGTYPE_p_double.getCPtr(mExtent));
  }

  public int GetMs(SWIGTYPE_p_double mArray) {
    return EsriFileGdbJNI.MultiPartShapeBuffer_GetMs(swigCPtr, this, SWIGTYPE_p_double.getCPtr(mArray));
  }

  public int GetNumCurves(SWIGTYPE_p_int numCurves) {
    return EsriFileGdbJNI.MultiPartShapeBuffer_GetNumCurves(swigCPtr, this, SWIGTYPE_p_int.getCPtr(numCurves));
  }

  public int GetCurves(SWIGTYPE_p_unsigned_char curves) {
    return EsriFileGdbJNI.MultiPartShapeBuffer_GetCurves(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(curves));
  }

  public int GetIDs(SWIGTYPE_p_int ids) {
    return EsriFileGdbJNI.MultiPartShapeBuffer_GetIDs(swigCPtr, this, SWIGTYPE_p_int.getCPtr(ids));
  }

  public int Setup(ShapeType shapeType, int numParts, int numPoints, int numCurves) {
    return EsriFileGdbJNI.MultiPartShapeBuffer_Setup__SWIG_0(swigCPtr, this, shapeType.swigValue(), numParts, numPoints, numCurves);
  }

  public int Setup(ShapeType shapeType, int numParts, int numPoints) {
    return EsriFileGdbJNI.MultiPartShapeBuffer_Setup__SWIG_1(swigCPtr, this, shapeType.swigValue(), numParts, numPoints);
  }

  public int CalculateExtent() {
    return EsriFileGdbJNI.MultiPartShapeBuffer_CalculateExtent(swigCPtr, this);
  }

  public int PackCurves() {
    return EsriFileGdbJNI.MultiPartShapeBuffer_PackCurves(swigCPtr, this);
  }

  public MultiPartShapeBuffer() {
    this(EsriFileGdbJNI.new_MultiPartShapeBuffer(), true);
  }

}
