/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.revolsys.gis.esri.gdb.file.swig;

public class MultiPointShapeBuffer extends ShapeBuffer {
  private long swigCPtr;

  protected MultiPointShapeBuffer(long cPtr, boolean cMemoryOwn) {
    super(EsriFileGdbJNI.SWIGMultiPointShapeBufferUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MultiPointShapeBuffer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        EsriFileGdbJNI.delete_MultiPointShapeBuffer(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public int GetExtent(SWIGTYPE_p_double extent) {
    return EsriFileGdbJNI.MultiPointShapeBuffer_GetExtent(swigCPtr, this, SWIGTYPE_p_double.getCPtr(extent));
  }

  public int GetNumPoints(SWIGTYPE_p_int numPoints) {
    return EsriFileGdbJNI.MultiPointShapeBuffer_GetNumPoints(swigCPtr, this, SWIGTYPE_p_int.getCPtr(numPoints));
  }

  public int GetPoints(Point points) {
    return EsriFileGdbJNI.MultiPointShapeBuffer_GetPoints(swigCPtr, this, Point.getCPtr(points), points);
  }

  public int GetZExtent(SWIGTYPE_p_double zExtent) {
    return EsriFileGdbJNI.MultiPointShapeBuffer_GetZExtent(swigCPtr, this, SWIGTYPE_p_double.getCPtr(zExtent));
  }

  public int GetZs(SWIGTYPE_p_double zArray) {
    return EsriFileGdbJNI.MultiPointShapeBuffer_GetZs(swigCPtr, this, SWIGTYPE_p_double.getCPtr(zArray));
  }

  public int GetMExtent(SWIGTYPE_p_double mExtent) {
    return EsriFileGdbJNI.MultiPointShapeBuffer_GetMExtent(swigCPtr, this, SWIGTYPE_p_double.getCPtr(mExtent));
  }

  public int GetMs(SWIGTYPE_p_double mArray) {
    return EsriFileGdbJNI.MultiPointShapeBuffer_GetMs(swigCPtr, this, SWIGTYPE_p_double.getCPtr(mArray));
  }

  public int GetIDs(SWIGTYPE_p_int ids) {
    return EsriFileGdbJNI.MultiPointShapeBuffer_GetIDs(swigCPtr, this, SWIGTYPE_p_int.getCPtr(ids));
  }

  public int Setup(ShapeType shapeType, int numPoints) {
    return EsriFileGdbJNI.MultiPointShapeBuffer_Setup(swigCPtr, this, shapeType.swigValue(), numPoints);
  }

  public int CalculateExtent() {
    return EsriFileGdbJNI.MultiPointShapeBuffer_CalculateExtent(swigCPtr, this);
  }

  public MultiPointShapeBuffer() {
    this(EsriFileGdbJNI.new_MultiPointShapeBuffer(), true);
  }

}
