/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.revolsys.gis.esri.gdb.file.swig;

public class PointShapeBuffer extends ShapeBuffer {
  private long swigCPtr;

  protected PointShapeBuffer(long cPtr, boolean cMemoryOwn) {
    super(EsriFileGdbJNI.SWIGPointShapeBufferUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PointShapeBuffer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        EsriFileGdbJNI.delete_PointShapeBuffer(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public int GetPoint(Point point) {
    return EsriFileGdbJNI.PointShapeBuffer_GetPoint(swigCPtr, this, Point.getCPtr(point), point);
  }

  public int GetZ(SWIGTYPE_p_double z) {
    return EsriFileGdbJNI.PointShapeBuffer_GetZ(swigCPtr, this, SWIGTYPE_p_double.getCPtr(z));
  }

  public int GetM(SWIGTYPE_p_double m) {
    return EsriFileGdbJNI.PointShapeBuffer_GetM(swigCPtr, this, SWIGTYPE_p_double.getCPtr(m));
  }

  public int GetID(SWIGTYPE_p_int id) {
    return EsriFileGdbJNI.PointShapeBuffer_GetID(swigCPtr, this, SWIGTYPE_p_int.getCPtr(id));
  }

  public int Setup(ShapeType shapeType) {
    return EsriFileGdbJNI.PointShapeBuffer_Setup(swigCPtr, this, shapeType.swigValue());
  }

  public PointShapeBuffer() {
    this(EsriFileGdbJNI.new_PointShapeBuffer(), true);
  }

}
