/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.revolsys.gis.esri.gdb.file.swig;

public class Point {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Point(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Point obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        EsriFileGdbJNI.delete_Point(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setX(double value) {
    EsriFileGdbJNI.Point_x_set(swigCPtr, this, value);
  }

  public double getX() {
    return EsriFileGdbJNI.Point_x_get(swigCPtr, this);
  }

  public void setY(double value) {
    EsriFileGdbJNI.Point_y_set(swigCPtr, this, value);
  }

  public double getY() {
    return EsriFileGdbJNI.Point_y_get(swigCPtr, this);
  }

  public Point() {
    this(EsriFileGdbJNI.new_Point(), true);
  }

}
