/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.revolsys.gis.esri.gdb.file.swig;

public class PointArrayValue {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected PointArrayValue(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PointArrayValue obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        EsriFileGdbJNI.delete_PointArrayValue(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public PointArrayValue() {
    this(EsriFileGdbJNI.new_PointArrayValue(), true);
  }

  public Point get(int i) {
    return new Point(EsriFileGdbJNI.PointArrayValue_get(swigCPtr, this, i), false);
  }

  public void set(int i, Point value) {
    EsriFileGdbJNI.PointArrayValue_set(swigCPtr, this, i, Point.getCPtr(value), value);
  }

}
