/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.revolsys.gis.esri.gdb.file.swig;

public class Row {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Row(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Row obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        EsriFileGdbJNI.delete_Row(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public int IsNull(String field, BoolValue isNull) {
    return EsriFileGdbJNI.Row_IsNull(swigCPtr, this, field, isNull);
  }

  public int SetNull(String field) {
    return EsriFileGdbJNI.Row_SetNull(swigCPtr, this, field);
  }

  public int GetOID(IntValue objectID) {
    return EsriFileGdbJNI.Row_GetOID(swigCPtr, this, objectID);
  }

  public int GetGlobalID(Guid globalID) {
    return EsriFileGdbJNI.Row_GetGlobalID(swigCPtr, this, Guid.getCPtr(globalID), globalID);
  }

  public int GetGeometry(ShapeBuffer shapeBuffer) {
    return EsriFileGdbJNI.Row_GetGeometry(swigCPtr, this, ShapeBuffer.getCPtr(shapeBuffer), shapeBuffer);
  }

  public int SetGeometry(ShapeBuffer shapeBuffer) {
    return EsriFileGdbJNI.Row_SetGeometry(swigCPtr, this, ShapeBuffer.getCPtr(shapeBuffer), shapeBuffer);
  }

  public int GetShort(String field, ShortValue value) {
    return EsriFileGdbJNI.Row_GetShort(swigCPtr, this, field, value);
  }

  public int SetShort(String field, short value) {
    return EsriFileGdbJNI.Row_SetShort(swigCPtr, this, field, value);
  }

  public int GetInteger(String field, IntValue value) {
    return EsriFileGdbJNI.Row_GetInteger(swigCPtr, this, field, value);
  }

  public int SetInteger(String field, int value) {
    return EsriFileGdbJNI.Row_SetInteger(swigCPtr, this, field, value);
  }

  public int GetFloat(String field, FloatValue value) {
    return EsriFileGdbJNI.Row_GetFloat(swigCPtr, this, field, value);
  }

  public int SetFloat(String field, float value) {
    return EsriFileGdbJNI.Row_SetFloat(swigCPtr, this, field, value);
  }

  public int GetDouble(String field, DoubleValue value) {
    return EsriFileGdbJNI.Row_GetDouble(swigCPtr, this, field, value);
  }

  public int SetDouble(String field, double value) {
    return EsriFileGdbJNI.Row_SetDouble(swigCPtr, this, field, value);
  }

  public int GetDate(String field, SWIGTYPE_p_tm value) {
    return EsriFileGdbJNI.Row_GetDate(swigCPtr, this, field, SWIGTYPE_p_tm.getCPtr(value));
  }

  public int SetDate(String field, SWIGTYPE_p_tm value) {
    return EsriFileGdbJNI.Row_SetDate(swigCPtr, this, field, SWIGTYPE_p_tm.getCPtr(value));
  }

  public int GetString(String field, WStringValue value) {
    return EsriFileGdbJNI.Row_GetString(swigCPtr, this, field, value);
  }

  public int SetString(String field, String value) {
    return EsriFileGdbJNI.Row_SetString(swigCPtr, this, field, value);
  }

  public int GetGUID(String field, Guid value) {
    return EsriFileGdbJNI.Row_GetGUID(swigCPtr, this, field, Guid.getCPtr(value), value);
  }

  public int SetGUID(String field, Guid value) {
    return EsriFileGdbJNI.Row_SetGUID(swigCPtr, this, field, Guid.getCPtr(value), value);
  }

  public int GetXML(String field, StringValue value) {
    return EsriFileGdbJNI.Row_GetXML(swigCPtr, this, field, value);
  }

  public int SetXML(String field, String value) {
    return EsriFileGdbJNI.Row_SetXML(swigCPtr, this, field, value);
  }

  public int GetRaster(String field, Raster raster) {
    return EsriFileGdbJNI.Row_GetRaster(swigCPtr, this, field, Raster.getCPtr(raster), raster);
  }

  public int SetRaster(String field, Raster raster) {
    return EsriFileGdbJNI.Row_SetRaster(swigCPtr, this, field, Raster.getCPtr(raster), raster);
  }

  public int GetBinary(String field, ByteArray binaryBuf) {
    return EsriFileGdbJNI.Row_GetBinary(swigCPtr, this, field, ByteArray.getCPtr(binaryBuf), binaryBuf);
  }

  public int SetBinary(String field, ByteArray binaryBuf) {
    return EsriFileGdbJNI.Row_SetBinary(swigCPtr, this, field, ByteArray.getCPtr(binaryBuf), binaryBuf);
  }

  public int GetFieldInformation(FieldInfo fieldInfo) {
    return EsriFileGdbJNI.Row_GetFieldInformation(swigCPtr, this, FieldInfo.getCPtr(fieldInfo), fieldInfo);
  }

  public Row() {
    this(EsriFileGdbJNI.new_Row(), true);
  }

}
