/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.revolsys.gis.esri.gdb.file.swig;

public class ShapeTypeValue {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ShapeTypeValue(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ShapeTypeValue obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        EsriFileGdbJNI.delete_ShapeTypeValue(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setValue(ShapeType value) {
    EsriFileGdbJNI.ShapeTypeValue_value_set(swigCPtr, this, value.swigValue());
  }

  public ShapeType getValue() {
    return ShapeType.swigToEnum(EsriFileGdbJNI.ShapeTypeValue_value_get(swigCPtr, this));
  }

  public ShapeTypeValue() {
    this(EsriFileGdbJNI.new_ShapeTypeValue(), true);
  }

}
