/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.revolsys.gis.esri.gdb.file.swig;

public class Texture {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Texture(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Texture obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        EsriFileGdbJNI.delete_Texture(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCount(int value) {
    EsriFileGdbJNI.Texture_count_set(swigCPtr, this, value);
  }

  public int getCount() {
    return EsriFileGdbJNI.Texture_count_get(swigCPtr, this);
  }

  public void setDimension(int value) {
    EsriFileGdbJNI.Texture_dimension_set(swigCPtr, this, value);
  }

  public int getDimension() {
    return EsriFileGdbJNI.Texture_dimension_get(swigCPtr, this);
  }

  public IntArray getParts() {
  return new IntArray(EsriFileGdbJNI.Texture_getParts(swigCPtr, this), false);
}

  public FloatArray getCoords() {
  return new FloatArray(EsriFileGdbJNI.Texture_getCoords(swigCPtr, this), false);
}

  public Texture() {
    this(EsriFileGdbJNI.new_Texture(), true);
  }

}
