/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.revolsys.gis.esri.gdb.file.swig;

public class UnsignedCharArray {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected UnsignedCharArray(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(UnsignedCharArray obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        EsriFileGdbJNI.delete_UnsignedCharArray(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public UnsignedCharArray(int nelements) {
    this(EsriFileGdbJNI.new_UnsignedCharArray(nelements), true);
  }

  public short getitem(int index) {
    return EsriFileGdbJNI.UnsignedCharArray_getitem(swigCPtr, this, index);
  }

  public void setitem(int index, short value) {
    EsriFileGdbJNI.UnsignedCharArray_setitem(swigCPtr, this, index, value);
  }

  public SWIGTYPE_p_unsigned_char cast() {
    long cPtr = EsriFileGdbJNI.UnsignedCharArray_cast(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public static UnsignedCharArray frompointer(SWIGTYPE_p_unsigned_char t) {
    long cPtr = EsriFileGdbJNI.UnsignedCharArray_frompointer(SWIGTYPE_p_unsigned_char.getCPtr(t));
    return (cPtr == 0) ? null : new UnsignedCharArray(cPtr, false);
  }

}
