/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.revolsys.gis.esri.gdb.file.swig;

public class UnsignedCharArray {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected UnsignedCharArray(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(UnsignedCharArray obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      EsriFileGdbJNI.delete_UnsignedCharArray(swigCPtr);
    }
    swigCPtr = 0;
  }

  public UnsignedCharArray() {
    this(EsriFileGdbJNI.new_UnsignedCharArray(), true);
  }

  public short get(int i) {
    return EsriFileGdbJNI.UnsignedCharArray_get(swigCPtr, this, i);
  }

  public void set(int i, short value) {
    EsriFileGdbJNI.UnsignedCharArray_set(swigCPtr, this, i, value);
  }

}
