/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.gdal.gdal;

public class MajorObject {
  protected static long getCPtr(final MajorObject obj) {
    return obj == null ? 0 : obj.swigCPtr;
  }

  private long swigCPtr;

  protected boolean swigCMemOwn;

  protected MajorObject(final long cPtr, final boolean cMemoryOwn) {
    if (cPtr == 0) {
      throw new RuntimeException();
    }
    this.swigCMemOwn = cMemoryOwn;
    this.swigCPtr = cPtr;
  }

  /* Ensure that the GC doesn't collect any parent instance set from Java */
  protected void addReference(final Object reference) {
  }

  public synchronized void delete() {
    if (this.swigCPtr != 0) {
      if (this.swigCMemOwn) {
        this.swigCMemOwn = false;
        throw new UnsupportedOperationException("C++ destructor does not have public access");
      }
      this.swigCPtr = 0;
    }
  }

  public String GetDescription() {
    return gdalJNI.MajorObject_GetDescription(this.swigCPtr, this);
  }

  public java.util.Hashtable GetMetadata_Dict() {
    return gdalJNI.MajorObject_GetMetadata_Dict__SWIG_1(this.swigCPtr, this);
  }

  public java.util.Hashtable GetMetadata_Dict(final String pszDomain) {
    return gdalJNI.MajorObject_GetMetadata_Dict__SWIG_0(this.swigCPtr, this, pszDomain);
  }

  public java.util.Vector GetMetadata_List() {
    return gdalJNI.MajorObject_GetMetadata_List__SWIG_1(this.swigCPtr, this);
  }

  public java.util.Vector GetMetadata_List(final String pszDomain) {
    return gdalJNI.MajorObject_GetMetadata_List__SWIG_0(this.swigCPtr, this, pszDomain);
  }

  public java.util.Vector GetMetadataDomainList() {
    return gdalJNI.MajorObject_GetMetadataDomainList(this.swigCPtr, this);
  }

  public String GetMetadataItem(final String pszName) {
    return gdalJNI.MajorObject_GetMetadataItem__SWIG_1(this.swigCPtr, this, pszName);
  }

  public String GetMetadataItem(final String pszName, final String pszDomain) {
    return gdalJNI.MajorObject_GetMetadataItem__SWIG_0(this.swigCPtr, this, pszName, pszDomain);
  }

  public void SetDescription(final String pszNewDesc) {
    gdalJNI.MajorObject_SetDescription(this.swigCPtr, this, pszNewDesc);
  }

  public int SetMetadata(final java.util.Hashtable metadata) {
    return SetMetadata(metadata, null);
  }

  /* For backward compatibilty */
  public int SetMetadata(final java.util.Hashtable metadata, final String domain) {
    if (metadata == null) {
      return SetMetadata((java.util.Vector)null, domain);
    }
    final java.util.Vector v = new java.util.Vector();
    final java.util.Enumeration values = metadata.elements();
    final java.util.Enumeration keys = metadata.keys();
    while (keys.hasMoreElements()) {
      v.add((String)keys.nextElement() + "=" + (String)values.nextElement());
    }
    return SetMetadata(v, domain);
  }

  public int SetMetadata(final java.util.Vector papszMetadata) {
    return gdalJNI.MajorObject_SetMetadata__SWIG_1(this.swigCPtr, this, papszMetadata);
  }

  public int SetMetadata(final java.util.Vector papszMetadata, final String pszDomain) {
    return gdalJNI.MajorObject_SetMetadata__SWIG_0(this.swigCPtr, this, papszMetadata, pszDomain);
  }

  public int SetMetadata(final String pszMetadataString) {
    return gdalJNI.MajorObject_SetMetadata__SWIG_3(this.swigCPtr, this, pszMetadataString);
  }

  public int SetMetadata(final String pszMetadataString, final String pszDomain) {
    return gdalJNI.MajorObject_SetMetadata__SWIG_2(this.swigCPtr, this, pszMetadataString,
      pszDomain);
  }

  public int SetMetadataItem(final String pszName, final String pszValue) {
    return gdalJNI.MajorObject_SetMetadataItem__SWIG_1(this.swigCPtr, this, pszName, pszValue);
  }

  public int SetMetadataItem(final String pszName, final String pszValue, final String pszDomain) {
    return gdalJNI.MajorObject_SetMetadataItem__SWIG_0(this.swigCPtr, this, pszName, pszValue,
      pszDomain);
  }

}
