/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.gdal.gdal;

public class RasterAttributeTable implements Cloneable {
  protected static long getCPtr(final RasterAttributeTable obj) {
    return obj == null ? 0 : obj.swigCPtr;
  }
  private long swigCPtr;

  protected boolean swigCMemOwn;

  public RasterAttributeTable() {
    this(gdalJNI.new_RasterAttributeTable(), true);
  }

  protected RasterAttributeTable(final long cPtr, final boolean cMemoryOwn) {
    if (cPtr == 0) {
      throw new RuntimeException();
    }
    this.swigCMemOwn = cMemoryOwn;
    this.swigCPtr = cPtr;
  }

  public int ChangesAreWrittenToFile() {
    return gdalJNI.RasterAttributeTable_ChangesAreWrittenToFile(this.swigCPtr, this);
  }


  @Override
  public Object clone()
  {
    return Clone();
  }

  public RasterAttributeTable Clone() {
    final long cPtr = gdalJNI.RasterAttributeTable_Clone(this.swigCPtr, this);
    return cPtr == 0 ? null : new RasterAttributeTable(cPtr, true);
  }

  public int CreateColumn(final String pszName, final int eType, final int eUsage) {
    return gdalJNI.RasterAttributeTable_CreateColumn(this.swigCPtr, this, pszName, eType, eUsage);
  }

  public synchronized void delete() {
    if (this.swigCPtr != 0) {
      if (this.swigCMemOwn) {
        this.swigCMemOwn = false;
        gdalJNI.delete_RasterAttributeTable(this.swigCPtr);
      }
      this.swigCPtr = 0;
    }
  }

  @Override
  protected void finalize() {
    delete();
  }

  public int GetColOfUsage(final int eUsage) {
    return gdalJNI.RasterAttributeTable_GetColOfUsage(this.swigCPtr, this, eUsage);
  }

  public int GetColumnCount() {
    return gdalJNI.RasterAttributeTable_GetColumnCount(this.swigCPtr, this);
  }

  public boolean GetLinearBinning(final double[] pdfRow0Min, final double[] pdfBinSize) {
    return gdalJNI.RasterAttributeTable_GetLinearBinning(this.swigCPtr, this, pdfRow0Min, pdfBinSize);
  }

  public String GetNameOfCol(final int iCol) {
    return gdalJNI.RasterAttributeTable_GetNameOfCol(this.swigCPtr, this, iCol);
  }

  public int GetRowCount() {
    return gdalJNI.RasterAttributeTable_GetRowCount(this.swigCPtr, this);
  }

  public int GetRowOfValue(final double dfValue) {
    return gdalJNI.RasterAttributeTable_GetRowOfValue(this.swigCPtr, this, dfValue);
  }

  public int GetTypeOfCol(final int iCol) {
    return gdalJNI.RasterAttributeTable_GetTypeOfCol(this.swigCPtr, this, iCol);
  }

  public int GetUsageOfCol(final int iCol) {
    return gdalJNI.RasterAttributeTable_GetUsageOfCol(this.swigCPtr, this, iCol);
  }

  public double GetValueAsDouble(final int iRow, final int iCol) {
    return gdalJNI.RasterAttributeTable_GetValueAsDouble(this.swigCPtr, this, iRow, iCol);
  }

  public int GetValueAsInt(final int iRow, final int iCol) {
    return gdalJNI.RasterAttributeTable_GetValueAsInt(this.swigCPtr, this, iRow, iCol);
  }

  public String GetValueAsString(final int iRow, final int iCol) {
    return gdalJNI.RasterAttributeTable_GetValueAsString(this.swigCPtr, this, iRow, iCol);
  }

  public int SetLinearBinning(final double dfRow0Min, final double dfBinSize) {
    return gdalJNI.RasterAttributeTable_SetLinearBinning(this.swigCPtr, this, dfRow0Min, dfBinSize);
  }

  public void SetRowCount(final int nCount) {
    gdalJNI.RasterAttributeTable_SetRowCount(this.swigCPtr, this, nCount);
  }

  public void SetValueAsDouble(final int iRow, final int iCol, final double dfValue) {
    gdalJNI.RasterAttributeTable_SetValueAsDouble(this.swigCPtr, this, iRow, iCol, dfValue);
  }

  public void SetValueAsInt(final int iRow, final int iCol, final int nValue) {
    gdalJNI.RasterAttributeTable_SetValueAsInt(this.swigCPtr, this, iRow, iCol, nValue);
  }

  public void SetValueAsString(final int iRow, final int iCol, final String pszValue) {
    gdalJNI.RasterAttributeTable_SetValueAsString(this.swigCPtr, this, iRow, iCol, pszValue);
  }

}
