"TRANSPORT_LINE_ID" IS NULL
AND "TRANSPORT_LINE_ID" IS NOT NULL
AND NOT (
  "EXCLUDED_RULES" = 'test'
  OR "EXCLUDED_RULES" <> 'test'
  OR FROM_VEHICLE_MAX_HEIGHT_METRE > 5
  OR "FROM_VEHICLE_MAX_HEIGHT_METRE" >= 5
  OR "FROM_VEHICLE_MAX_HEIGHT_METRE" < 5.1
  OR "FROM_VEHICLE_MAX_HEIGHT_METRE" <= 5.1
  OR "TRANSPORT_LINE_ID" IN (1,2,3,4)
  OR "TRANSPORT_LINE_ID" LIKE 'y%7'
  OR "TRANSPORT_LINE_ID" BETWEEN 1 AND 5
)
AND CAPTURE_DATE = {t '11:15:34'}
AND CAPTURE_DATE = {d '2013-05-04'}
AND CAPTURE_DATE = {ts '2013-05-04 11:15:34.567'}
