/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.39
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.gdal.ogr;

public class FeatureDefn {
  protected static long getCPtr(final FeatureDefn obj) {
    return obj == null ? 0 : obj.swigCPtr;
  }

  protected static long getCPtrAndDisown(final FeatureDefn obj) {
    if (obj != null) {
      obj.swigCMemOwn = false;
    }
    return getCPtr(obj);
  }

  private long swigCPtr;

  protected boolean swigCMemOwn;

  public FeatureDefn() {
    this(ogrJNI.new_FeatureDefn__SWIG_1(), true);
  }

  protected FeatureDefn(final long cPtr, final boolean cMemoryOwn) {
    if (cPtr == 0) {
      throw new RuntimeException();
    }
    this.swigCMemOwn = cMemoryOwn;
    this.swigCPtr = cPtr;
  }

  public FeatureDefn(final String name_null_ok) {
    this(ogrJNI.new_FeatureDefn__SWIG_0(name_null_ok), true);
  }

  public void AddFieldDefn(final FieldDefn defn) {
    ogrJNI.FeatureDefn_AddFieldDefn(this.swigCPtr, this,
      FieldDefn.getCPtr(defn), defn);
  }

  public void AddGeomFieldDefn(final GeomFieldDefn defn) {
    ogrJNI.FeatureDefn_AddGeomFieldDefn(this.swigCPtr, this,
      GeomFieldDefn.getCPtr(defn), defn);
  }

  /* Ensure that the GC doesn't collect any parent instance set from Java */
  protected void addReference(final Object reference) {
  }

  public synchronized void delete() {
    if (this.swigCPtr != 0 && this.swigCMemOwn) {
      this.swigCMemOwn = false;
      ogrJNI.delete_FeatureDefn(this.swigCPtr);
    }
    this.swigCPtr = 0;
  }

  public int DeleteGeomFieldDefn(final int idx) {
    return ogrJNI.FeatureDefn_DeleteGeomFieldDefn(this.swigCPtr, this, idx);
  }

  @Override
  public boolean equals(final Object obj) {
    boolean equal = false;
    if (obj instanceof FeatureDefn) {
      equal = ((FeatureDefn)obj).swigCPtr == this.swigCPtr;
    }
    return equal;
  }

  @Override
  protected void finalize() {
    delete();
  }

  public int GetFieldCount() {
    return ogrJNI.FeatureDefn_GetFieldCount(this.swigCPtr, this);
  }

  public FieldDefn GetFieldDefn(final int i) {
    final long cPtr = ogrJNI.FeatureDefn_GetFieldDefn(this.swigCPtr, this, i);
    FieldDefn ret = null;
    if (cPtr != 0) {
      ret = new FieldDefn(cPtr, false);
      ret.addReference(this);
    }
    return ret;
  }

  public int GetFieldIndex(final String name) {
    return ogrJNI.FeatureDefn_GetFieldIndex(this.swigCPtr, this, name);
  }

  public int GetGeomFieldCount() {
    return ogrJNI.FeatureDefn_GetGeomFieldCount(this.swigCPtr, this);
  }

  public GeomFieldDefn GetGeomFieldDefn(final int i) {
    final long cPtr = ogrJNI.FeatureDefn_GetGeomFieldDefn(this.swigCPtr, this,
      i);
    return cPtr == 0 ? null : new GeomFieldDefn(cPtr, false);
  }

  public int GetGeomFieldIndex(final String name) {
    return ogrJNI.FeatureDefn_GetGeomFieldIndex(this.swigCPtr, this, name);
  }

  public int GetGeomType() {
    return ogrJNI.FeatureDefn_GetGeomType(this.swigCPtr, this);
  }

  public String GetName() {
    return ogrJNI.FeatureDefn_GetName(this.swigCPtr, this);
  }

  public int GetReferenceCount() {
    return ogrJNI.FeatureDefn_GetReferenceCount(this.swigCPtr, this);
  }

  @Override
  public int hashCode() {
    return (int)this.swigCPtr;
  }

  public int IsGeometryIgnored() {
    return ogrJNI.FeatureDefn_IsGeometryIgnored(this.swigCPtr, this);
  }

  public int IsSame(final FeatureDefn other_defn) {
    return ogrJNI.FeatureDefn_IsSame(this.swigCPtr, this,
      FeatureDefn.getCPtr(other_defn), other_defn);
  }

  public int IsStyleIgnored() {
    return ogrJNI.FeatureDefn_IsStyleIgnored(this.swigCPtr, this);
  }

  public void SetGeometryIgnored(final int bIgnored) {
    ogrJNI.FeatureDefn_SetGeometryIgnored(this.swigCPtr, this, bIgnored);
  }

  public void SetGeomType(final int geom_type) {
    ogrJNI.FeatureDefn_SetGeomType(this.swigCPtr, this, geom_type);
  }

  public void SetStyleIgnored(final int bIgnored) {
    ogrJNI.FeatureDefn_SetStyleIgnored(this.swigCPtr, this, bIgnored);
  }

}
