/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.gdal.ogr;

public class Feature implements Cloneable {
  protected static long getCPtr(final Feature obj) {
    return obj == null ? 0 : obj.swigCPtr;
  }

  private final long swigCPtr;

  private FeatureNative nativeObject;

  public Feature(final FeatureDefn feature_def) {
    this(ogrJNI.new_Feature(FeatureDefn.getCPtr(feature_def), feature_def), true);
  }

  protected Feature(final long cPtr, final boolean cMemoryOwn) {
    if (cPtr == 0) {
      throw new RuntimeException();
    }
    this.swigCPtr = cPtr;
    if (cMemoryOwn) {
      this.nativeObject = new FeatureNative(this, cPtr);
    }
  }

  @Override
  public Object clone() {
    return Clone();
  }

  public Feature Clone() {
    final long cPtr = ogrJNI.Feature_Clone(this.swigCPtr, this);
    return cPtr == 0 ? null : new Feature(cPtr, true);
  }

  public void delete() {
    if (this.nativeObject != null) {
      this.nativeObject.delete();
      this.nativeObject = null;
    }
  }

  public void DumpReadable() {
    ogrJNI.Feature_DumpReadable(this.swigCPtr, this);
  }

  public boolean Equal(final Feature feature) {
    return ogrJNI.Feature_Equal(this.swigCPtr, this, Feature.getCPtr(feature), feature);
  }

  @Override
  public boolean equals(final Object obj) {
    boolean equal = false;
    if (obj instanceof Feature) {
      equal = Equal((Feature)obj);
    }
    return equal;
  }

  public FeatureDefn GetDefnRef() {
    final long cPtr = ogrJNI.Feature_GetDefnRef(this.swigCPtr, this);
    FeatureDefn ret = null;
    if (cPtr != 0) {
      ret = new FeatureDefn(cPtr, false);
      ret.addReference(this);
    }
    return ret;
  }

  public int GetFID() {
    return ogrJNI.Feature_GetFID(this.swigCPtr, this);
  }

  public void GetFieldAsDateTime(final int id, final int[] pnYear, final int[] pnMonth,
    final int[] pnDay, final int[] pnHour, final int[] pnMinute, final int[] pnSecond,
    final int[] pnTZFlag) {
    ogrJNI.Feature_GetFieldAsDateTime(this.swigCPtr, this, id, pnYear, pnMonth, pnDay, pnHour,
      pnMinute, pnSecond, pnTZFlag);
  }

  public double GetFieldAsDouble(final int id) {
    return ogrJNI.Feature_GetFieldAsDouble__SWIG_0(this.swigCPtr, this, id);
  }

  public double GetFieldAsDouble(final String name) {
    return ogrJNI.Feature_GetFieldAsDouble__SWIG_1(this.swigCPtr, this, name);
  }

  public double[] GetFieldAsDoubleList(final int id) {
    return ogrJNI.Feature_GetFieldAsDoubleList(this.swigCPtr, this, id);
  }

  public int GetFieldAsInteger(final int id) {
    return ogrJNI.Feature_GetFieldAsInteger__SWIG_0(this.swigCPtr, this, id);
  }

  public int GetFieldAsInteger(final String name) {
    return ogrJNI.Feature_GetFieldAsInteger__SWIG_1(this.swigCPtr, this, name);
  }

  public int[] GetFieldAsIntegerList(final int id) {
    return ogrJNI.Feature_GetFieldAsIntegerList(this.swigCPtr, this, id);
  }

  public String GetFieldAsString(final int id) {
    return ogrJNI.Feature_GetFieldAsString__SWIG_0(this.swigCPtr, this, id);
  }

  public String GetFieldAsString(final String name) {
    return ogrJNI.Feature_GetFieldAsString__SWIG_1(this.swigCPtr, this, name);
  }

  public String[] GetFieldAsStringList(final int id) {
    return ogrJNI.Feature_GetFieldAsStringList(this.swigCPtr, this, id);
  }

  public int GetFieldCount() {
    return ogrJNI.Feature_GetFieldCount(this.swigCPtr, this);
  }

  public FieldDefn GetFieldDefnRef(final int id) {
    final long cPtr = ogrJNI.Feature_GetFieldDefnRef__SWIG_0(this.swigCPtr, this, id);
    FieldDefn ret = null;
    if (cPtr != 0) {
      ret = new FieldDefn(cPtr, false);
      ret.addReference(this);
    }
    return ret;
  }

  public FieldDefn GetFieldDefnRef(final String name) {
    final long cPtr = ogrJNI.Feature_GetFieldDefnRef__SWIG_1(this.swigCPtr, this, name);
    FieldDefn ret = null;
    if (cPtr != 0) {
      ret = new FieldDefn(cPtr, false);
      ret.addReference(this);
    }
    return ret;
  }

  public int GetFieldIndex(final String name) {
    return ogrJNI.Feature_GetFieldIndex(this.swigCPtr, this, name);
  }

  public int GetFieldType(final int id) {
    return ogrJNI.Feature_GetFieldType__SWIG_0(this.swigCPtr, this, id);
  }

  public int GetFieldType(final String name) {
    return ogrJNI.Feature_GetFieldType__SWIG_1(this.swigCPtr, this, name);
  }

  public Geometry GetGeometryRef() {
    final long cPtr = ogrJNI.Feature_GetGeometryRef(this.swigCPtr, this);
    Geometry ret = null;
    if (cPtr != 0) {
      ret = new Geometry(cPtr, false);
      ret.addReference(this);
    }
    return ret;
  }

  public int GetGeomFieldCount() {
    return ogrJNI.Feature_GetGeomFieldCount(this.swigCPtr, this);
  }

  public GeomFieldDefn GetGeomFieldDefnRef(final int id) {
    final long cPtr = ogrJNI.Feature_GetGeomFieldDefnRef__SWIG_0(this.swigCPtr, this, id);
    return cPtr == 0 ? null : new GeomFieldDefn(cPtr, false);
  }

  public GeomFieldDefn GetGeomFieldDefnRef(final String name) {
    final long cPtr = ogrJNI.Feature_GetGeomFieldDefnRef__SWIG_1(this.swigCPtr, this, name);
    return cPtr == 0 ? null : new GeomFieldDefn(cPtr, false);
  }

  public int GetGeomFieldIndex(final String name) {
    return ogrJNI.Feature_GetGeomFieldIndex(this.swigCPtr, this, name);
  }

  public Geometry GetGeomFieldRef(final int iField) {
    final long cPtr = ogrJNI.Feature_GetGeomFieldRef__SWIG_0(this.swigCPtr, this, iField);
    Geometry ret = null;
    if (cPtr != 0) {
      ret = new Geometry(cPtr, false);
      ret.addReference(this);
    }
    return ret;
  }

  public Geometry GetGeomFieldRef(final String name) {
    final long cPtr = ogrJNI.Feature_GetGeomFieldRef__SWIG_1(this.swigCPtr, this, name);
    Geometry ret = null;
    if (cPtr != 0) {
      ret = new Geometry(cPtr, false);
      ret.addReference(this);
    }
    return ret;
  }

  public String GetStyleString() {
    return ogrJNI.Feature_GetStyleString(this.swigCPtr, this);
  }

  @Override
  public int hashCode() {
    return (int)this.swigCPtr;
  }

  public boolean IsFieldSet(final int id) {
    return ogrJNI.Feature_IsFieldSet__SWIG_0(this.swigCPtr, this, id);
  }

  public boolean IsFieldSet(final String name) {
    return ogrJNI.Feature_IsFieldSet__SWIG_1(this.swigCPtr, this, name);
  }

  public int SetFID(final int fid) {
    return ogrJNI.Feature_SetFID(this.swigCPtr, this, fid);
  }

  public void SetField(final int id, final double value) {
    ogrJNI.Feature_SetField__SWIG_4(this.swigCPtr, this, id, value);
  }

  public void SetField(final int id, final int value) {
    ogrJNI.Feature_SetField__SWIG_2(this.swigCPtr, this, id, value);
  }

  public void SetField(final int id, final int year, final int month, final int day, final int hour,
    final int minute, final int second, final int tzflag) {
    ogrJNI.Feature_SetField__SWIG_6(this.swigCPtr, this, id, year, month, day, hour, minute, second,
      tzflag);
  }

  public void SetField(final int id, final String value) {
    ogrJNI.Feature_SetField__SWIG_0(this.swigCPtr, this, id, value);
  }

  public void SetField(final String name, final double value) {
    ogrJNI.Feature_SetField__SWIG_5(this.swigCPtr, this, name, value);
  }

  public void SetField(final String name, final int value) {
    ogrJNI.Feature_SetField__SWIG_3(this.swigCPtr, this, name, value);
  }

  public void SetField(final String name, final int year, final int month, final int day,
    final int hour, final int minute, final int second, final int tzflag) {
    ogrJNI.Feature_SetField__SWIG_7(this.swigCPtr, this, name, year, month, day, hour, minute,
      second, tzflag);
  }

  public void SetField(final String name, final String value) {
    ogrJNI.Feature_SetField__SWIG_1(this.swigCPtr, this, name, value);
  }

  public void SetFieldBinaryFromHexString(final int id, final String pszValue) {
    ogrJNI.Feature_SetFieldBinaryFromHexString__SWIG_0(this.swigCPtr, this, id, pszValue);
  }

  public void SetFieldBinaryFromHexString(final String name, final String pszValue) {
    ogrJNI.Feature_SetFieldBinaryFromHexString__SWIG_1(this.swigCPtr, this, name, pszValue);
  }

  public void SetFieldDoubleList(final int id, final double[] nList) {
    ogrJNI.Feature_SetFieldDoubleList(this.swigCPtr, this, id, nList);
  }

  public void SetFieldIntegerList(final int id, final int[] nList) {
    ogrJNI.Feature_SetFieldIntegerList(this.swigCPtr, this, id, nList);
  }

  public void SetFieldStringList(final int id, final java.util.Vector pList) {
    ogrJNI.Feature_SetFieldStringList(this.swigCPtr, this, id, pList);
  }

  public int SetFrom(final Feature other) {
    return ogrJNI.Feature_SetFrom__SWIG_1(this.swigCPtr, this, Feature.getCPtr(other), other);
  }

  public int SetFrom(final Feature other, final int forgiving) {
    return ogrJNI.Feature_SetFrom__SWIG_0(this.swigCPtr, this, Feature.getCPtr(other), other,
      forgiving);
  }

  public int SetFromWithMap(final Feature other, final int forgiving, final int[] nList) {
    return ogrJNI.Feature_SetFromWithMap(this.swigCPtr, this, Feature.getCPtr(other), other,
      forgiving, nList);
  }

  public int SetGeometry(final Geometry geom) {
    return ogrJNI.Feature_SetGeometry(this.swigCPtr, this, Geometry.getCPtr(geom), geom);
  }

  public int SetGeometryDirectly(final Geometry geom) {
    final int ret = ogrJNI.Feature_SetGeometryDirectly(this.swigCPtr, this,
      Geometry.getCPtrAndDisown(geom), geom);
    if (geom != null) {
      geom.addReference(this);
    }
    return ret;
  }

  public int SetGeomField(final int iField, final Geometry geom) {
    return ogrJNI.Feature_SetGeomField__SWIG_0(this.swigCPtr, this, iField, Geometry.getCPtr(geom),
      geom);
  }

  public int SetGeomField(final String name, final Geometry geom) {
    return ogrJNI.Feature_SetGeomField__SWIG_1(this.swigCPtr, this, name, Geometry.getCPtr(geom),
      geom);
  }

  public int SetGeomFieldDirectly(final int iField, final Geometry geom) {
    return ogrJNI.Feature_SetGeomFieldDirectly__SWIG_0(this.swigCPtr, this, iField,
      Geometry.getCPtrAndDisown(geom), geom);
  }

  public int SetGeomFieldDirectly(final String name, final Geometry geom) {
    return ogrJNI.Feature_SetGeomFieldDirectly__SWIG_1(this.swigCPtr, this, name,
      Geometry.getCPtrAndDisown(geom), geom);
  }

  public void SetStyleString(final String the_string) {
    ogrJNI.Feature_SetStyleString(this.swigCPtr, this, the_string);
  }

  public void UnsetField(final int id) {
    ogrJNI.Feature_UnsetField__SWIG_0(this.swigCPtr, this, id);
  }

  public void UnsetField(final String name) {
    ogrJNI.Feature_UnsetField__SWIG_1(this.swigCPtr, this, name);
  }

}
